### ISSUE TITLE
Output results of classic grid search

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#10]
The classic grid search runs fine, but we need to output the results for quick visual inspections.

For a (y,x) grid search, can we make an model.results file that looks something like:

centre_0, centre_1, likelihood
-1.0             1.0            10.0
-0.5             1.0            15.0
-0.0            1.0             22.0

etc.

**Comment by Jammy2211** [comment]
In fact, we need this for the optimizer grid search too, e.g. for the most probably model of every optimizer search.

**Comment by rhayes777** [comment]
Both implemented. A file called "results" will now appear in the phase directory.

**Comment by Jammy2211** [comment]
The 'results' file for the classic grid search does not output anything but the parameter names.

my NLO grid searches havent finished yet, but it would be good if their results file updated between every NLO run.

**Comment by rhayes777** [comment]
Oh that’s odd. Do NLO results contain fit?

**Comment by Jammy2211** [comment]
They dont contain anything called 'fit' i dont think?

**Comment by Jammy2211** [comment]
The NLO grid search was a bit more positive, giving a results file, but the centres (I guess because they were a tuple) were not both output, and neither were the scale radii / kappa_s:

`lens_galaxies_subhalo_scale_radius, lens_galaxies_subhalo_centre_0, lens_galaxies_subhalo_centre_1, lens_galaxies_subhalo_kappa_s
0.00, -2.00, 25889.32
0.00, -1.33, 25888.13
0.00, -0.67, 25887.45
0.00, 0.00, 25887.31
0.00, 0.67, 25886.82
0.00, 1.33, 25899.59
5.00, -2.00, 25889.40
5.00, -1.33, 25905.59
5.00, -0.67, 25889.02
5.00, 0.00, 25887.67
5.00, 0.67, 25908.23
5.00, 1.33, 25930.16
10.00, -2.00, 25895.46
10.00, -1.33, 25891.74
10.00, -0.67, 25890.29
10.00, 0.00, 25888.69
10.00, 0.67, 25911.50
10.00, 1.33, 25907.44
15.00, -2.00, 25906.09
15.00, -1.33, 25898.90
15.00, -0.67, 25889.97
15.00, 0.00, 25889.29
15.00, 0.67, 25889.20
15.00, 1.33, 25898.67
20.00, -2.00, 25909.84
20.00, -1.33, 25901.53
20.00, -0.67, 25889.63
20.00, 0.00, 25888.69
20.00, 0.67, 25902.47
20.00, 1.33, 25910.00
25.00, -2.00, 25910.13
25.00, -1.33, 25888.76
25.00, -0.67, 25888.47
25.00, 0.00, 25886.14
25.00, 0.67, 25888.53
25.00, 1.33, 25894.89`

It would be good also if we could have the spacing between parameters clearer and some summary stats (e.g. the maximum increase in likelihood and model which was the 'best') at the top. If you point me to where in autotfit this is I can probably do the summary stats.

**Comment by rhayes777** [comment]
I think this is resolved?

**Comment by rhayes777** [comment]
Bump
