### ISSUE TITLE
Project Restructuring for Euclid coding enviroment

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#102]
As we've discussed, for PyAutoFit to run on Euclid machines we have to conform to their coding framework EDEN. This is feasible via a series of carefully constructed macros that convert the autofit source code to be EDEN compliant, but there are constraints that mean structuring the autofit source code in a specific way will make things a lot easier.

**Test Imports**

The biggest handicap is that we cannot use a project level __ init __ method, meaning that we are unable to use the command "import autofit as af" in the source code, or more importantly the unit tests (we can keep this file here for non EDEN API, its just specifically internal unit tests we have a problem).

In PyAutoCTI, I over came this by having package level imports - I have an example below for the charge injectioon package:

```
from .ci_fit import CIFitImaging
from .ci_frame import CIFrame, MaskedCIFrame
from .ci_hyper import CIHyperNoiseScalar
from .ci_imaging import (
    CIImaging,
    MaskedCIImaging,
    SimulatorCIImaging,
)
from .ci_mask import CIMask
from .ci_pattern import CIPatternUniform, CIPatternNonUniform
```

In unit tests, such imports mean we can still keep them relatively import light as we can use just the following imports:

```
from autocti import structures as struct
from autocti import charge_injection as ci
```

Although this was a massive PITA to begin, by the end I actually preferred this to the project-level import as it makes it more explicit where the things we are testing come from. It also means the project supports package level imports, so its not to bad!

Is such a structure possible for AutoFit? I had a go at doing this, but ran into import conflict issues due to the mapper -> prior and mapper -> prior_model sub-package structure. The prior package actually already performs imports as required, but replicating this in prior_model causes hell to be unleashed. If this restructing is doable I'd say we shsould go ahead and do it!

**Unit test structure**

For writing the macros, it is a lot cleaner if the unit tests reflect the source code structure. This currently isn't the case with autofit, for example our source code structure is:

autofit
....mapper
........prior
........prior_model

Whereas the unit tests for this part of the code are:

test_autofit
....unit
........mapper
............model
............promise

Is there a reason the tests are structured in this way? If not, I'm happy to reshuffle things as needs be.

**mock objects**

The current set up of mock objects is not allowed, because we cannot store them in the directory test_autofit/mock/mock.py and import them. I am not 100% sure of the limitations of EDEN here yet, but provided we can import from a test directory my suggestion is that every test package (e.g. test_autofit/unit/mapper/) has its own mock.py file, as opposed to one Goliath file in the test directory. Although a PITA, I think this would again actually lead to more clean and well structured code in the long run.

**Import Restrictions**

EDEN supports a limited library of imports. Thus far, I've not hit any terrible barriers with what we are using in PyAutoFit (only typing_inspect is not suppoted), but if a major clash comes up we'll need to have a think.

**Comment by rhayes777** [comment]
We really shouldn't change the API unless we have to. I can see how changing the tests would make conversion easier, with us simply replacing the top level \_\_init\_\_ with an empty alternative. Even so it's a bit frustrating. I frequently want to reference some object from autofit and I don't want to have to remember where it is! 

As an aside, you don't need explicit imports to work out where the objects you're testing are. If you're still clicking through the directory structure you're not taking full advantage of PyCharm. ctrl + click will take you to the object you're importing. I don't know the other hotkeys on ubuntu but you should look up how you search everywhere, switch to recently opened files and search specifically for classes. 

I don't think unit test necessarily have a one to one correspondence to source code. Sometimes I am testing a new feature which corresponds to source code in an existing module but warrants its own test module. pytest fixture overriding can even make this distinct test directory structure unavoidable. 

I don't follow with the import thing. We certainly don't want to duplicate all our mock objects.

Do our tests have to run on Eden?

**Comment by Jammy2211** [comment]
The script thing works great!

In PyAutoFit we can turn the  'import autofit as af' command to separate import for our unit tests. However, we can't turn the 'import autofit as af' into separate import in the autocti project at all, which uses the command for both source code and unit tests.

Can we expand the scripts to allow this process to run through multiple project?

**Comment by Jammy2211** [comment]
Done.
