### ISSUE TITLE
Latent variables not scraping correctly

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#1042]
to reproduce this error you need to comment out the following two lines of code (188 - 189):

```
# assert latent_fwhm_param > 0.0
# assert latent_fwhm_instance.gaussian.fwhm > 0.0
```

The following script:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/scripts/database/scrape/general.py

Produces the following error:

```
<autofit.non_linear.search.nest.dynesty.search.static.DynestyStatic object at 0x7f7fdef6bd90>
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test/scripts/database/scrape/general.py", line 190, in <module>
    assert latent_fwhm_param > 0.0
NameError: name 'latent_fwhm_param' is not defined
```

A folder `files/latent.csv` is being correctly made with the latent variables, its just not being loaded for some reason.

Note that the following error is also printed:

`2024-08-31 19:51:51,632 - autofit.database.aggregator.scrape - WARNING - Failed to load latent variables for ae18b9ae8998bc6bdd77217134a0814c`

**Comment by rhayes777** [comment]
I found a fix for the specific issue although the call to parameter_lists now fails because the latent samples object has no model

**Comment by Jammy2211** [comment]
Can you fix the fact it has no model? Sounds like a bug still
