### ISSUE TITLE
Retrieve full list of grid search models w/ likelihood

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#11]
We need a function that after a grid search has run, allows us to retrieve the complete set of models with their likelihoods.

This is for visualization (e.g. the (y,x) grid of likelihoods of a sensitivity phase).

**Comment by rhayes777** [comment]
So in the classic grid search this would be model instances which can be directly visualised because all their parameters are fixed.

However, in the non linear grid search this is more subtle. What is produced for each grid point is a model mapper which may still contain priors.

**Comment by rhayes777** [comment]
I've implemented this for classic grid search
