### ISSUE TITLE
DOC: mpl backend claimed to be "default" but found to be "TKAgg"

### ISSUE THREAD

**Issue by arm61** [rhayes777/PyAutoFit#113]
In the installation docs it says that the `autofit_workspace` should have the `backend` as `default`. But cloning from `https://github.com/Jammy2211/autofit_workspace` gives a `backend=TKAgg`.

**Comment by Jammy2211** [comment]
Thanks - I've updated the workspace config to default so this will be fixed in the next release.

Our scripts which generate the HowToFit notebooks from Python scripts edit our config files to turn off visualization, so this is most likely a remnant of those scripts (I fixed them recently).
