### ISSUE TITLE
DOC: example doesn't work unless in the `autofit_workspace` directory

### ISSUE THREAD

**Issue by arm61** [rhayes777/PyAutoFit#115]
The `simple/fit.py` example doesn't work unless you are in the `autofit_workspace` directory. So the code snippet 

```
python3 /path/to/autofit_workspace/examples/simple/fit.py
```

Should probably be something like 
```
cd /path/to/autofit_workspace
python3 ./examples/simple/fit.py
```

**Comment by arm61** [comment]
Actually it seems like this isn't fixed in the same way as #116 sorry. The problem seems to be that there is a relative path when it is looking for the `DynestyStatic.ini` file. 

```
configparser.NoSectionError: No section: 'Could not find section search in config at path /Users/lno76132/config/non_linear/nest/DynestyStatic.ini'
```

When the file is in `/Users/lno76132/Downloads/config/non_linear/nest/DynestyStatic.ini` but it is assuming I am running from the same place as the `config` directory is pasted. (sorry that was terribly explained).

**Comment by Jammy2211** [comment]
`export WORKSPACE=/path/to/autofit_workspace/`

The WORKSPACE variable definitely does need the 'autofit_workspace' included.

**Comment by arm61** [comment]
```
>> echo $WORKSPACE
/Users/lno76132/Downloads/autofit_workspace/
>> echo $PYTHONPATH
/Users/lno76132/Downloads/
>> pwd 
/Users/lno76132/Downloads
>> python /Users/lno76132/Downloads/autofit_workspace/examples/simple/fit.py 
Workspace Path:  /Users/lno76132
ERROR:root:No section: 'Could not find section output in config at path /Users/lno76132/config/general.ini'
Traceback (most recent call last):
  File "/Users/lno76132/Downloads/autofit_workspace/venv/lib/python3.7/site-packages/autoconf/named.py", line 49, in get
    string_value = self.parser.get(section_name, attribute_name)
  File "/Users/lno76132/miniconda3/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/Users/lno76132/miniconda3/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'output'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lno76132/Downloads/autofit_workspace/venv/lib/python3.7/site-packages/autofit/non_linear/paths.py", line 143, in __init__
    self.remove_files = conf.instance.general.get("output", "remove_files", bool)
  File "/Users/lno76132/Downloads/autofit_workspace/venv/lib/python3.7/site-packages/autoconf/named.py", line 53, in get
    section_name, self.path
configparser.NoSectionError: No section: 'Could not find section output in config at path /Users/lno76132/config/general.ini'
Traceback (most recent call last):
  File "/Users/lno76132/Downloads/autofit_workspace/venv/lib/python3.7/site-packages/autoconf/named.py", line 49, in get
    string_value = self.parser.get(section_name, attribute_name)
  File "/Users/lno76132/miniconda3/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/Users/lno76132/miniconda3/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'search'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lno76132/Downloads/autofit_workspace/examples/simple/fit.py", line 136, in <module>
    paths=af.Paths(folders=["examples", "simple"]),
  File "/Users/lno76132/Downloads/autofit_workspace/venv/lib/python3.7/site-packages/autofit/non_linear/nest/dynesty.py", line 640, in __init__
    if evidence_tolerance is None
  File "/Users/lno76132/Downloads/autofit_workspace/venv/lib/python3.7/site-packages/autofit/non_linear/abstract_search.py", line 299, in _config
    section, attribute_name, attribute_type
  File "/Users/lno76132/Downloads/autofit_workspace/venv/lib/python3.7/site-packages/autoconf/named.py", line 53, in get
    section_name, self.path
configparser.NoSectionError: No section: 'Could not find section search in config at path /Users/lno76132/config/non_linear/nest/DynestyStatic.ini'
```

But if I change to the `autofit_workspace` dir

```
cd autofit_workspace/
python /Users/lno76132/Downloads/autofit_workspace/examples/simple/fit.py 
Workspace Path:  /Users/lno76132/Downloads/autofit_workspace
INFO:root: already completed, skipping non-linear search.
INFO:root: already completed, skipping non-linear search.
INFO:root: already completed, skipping non-linear search.
``` 

everything is happy (I have already run it before so it skips).

**Comment by Jammy2211** [comment]
The issue is this line:

```
# %%
from pyprojroot import here

workspace_path = str(here())
print("Workspace Path: ", workspace_path)
```

This line is meant to automatically determine the correct workspace path from the location of the file. It has always worked for our users but is something we only added recently, so it's thoroughly tested. Its coming up with the wrong workspace_path for you, which is why in your print it says:

> Workspace Path:  /Users/lno76132

I'm not sure whether this is because your PYTHONPATH isn't the autofit_workspace (thats my bad if so) or if its a general shortcoming of pyprojroot. It may be we simply haven't tested it extensively enough to see when it fails. 
 
It may be worth trying the code with the PYTHONPATH set as:

`export PYTHONPATH=/path/to/autofit_workspace/`

Which would require you to replace the `from autofit_workspace.` text with `from `, wherever they crop up. 

If this doesn't fix it for the general use case it's probably a sign pyprojroot doesn't always performed the way it has for us in a general setting.

**Comment by Jammy2211** [comment]
(FYI, we used to use relative paths in the example scripts to set up the workspace_path. The problem is you cannot use relative paths in Jupyter notebooks and thus wouldn't work for the HowToFit tutorials, which is why we switched to pyprojroot).

**Comment by Jammy2211** [comment]
Just did a test on my laptop, and I reproduce the error if I try to run the fit script when my location in the terminal is outside of autofit_workspace. I guess this changes the `PYTHONPATH` to a higher level directory, which means pyprojroot chooses that directory instead.

I will add a note to the docs that you must cd into the directory to avoid this issue.

**Comment by arm61** [comment]
So from playing about a bit. `pyprojroot` will only find the current project root. The problem is that I am going a directory up from `autofit_workspace`, if I go deeper (say into `howtofit`) everything is fine.

**Comment by arm61** [comment]
Yeah I tried changing

**Comment by arm61** [comment]
Sorry that close/open was a mis-click

**Comment by arm61** [comment]
This seems to be resolved. Closing.
