### ISSUE TITLE
Optimizer grid search does not work for redshift

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#12]
Working for the centres of a profile, but not for a galaxy redshift :O. The error is:

> Traceback (most recent call last):
>   File "/home/jammy/PyCharm/Projects/AutoLens/workspace_jam/runners/subhalo_runner.py", line 31, in <module>
>     pipeline.run(data=ccd_data)
>   File "/home/jammy/PyCharm/Projects/AutoLens/autolens/pipeline/pipeline.py", line 48, in run
>     positions=positions))
>   File "/home/jammy/PyCharm/Projects/AutoLens/autolens/pipeline/phase.py", line 459, in run
>     result = self.run_analysis(analysis)
>   File "/home/jammy/PyCharm/VirtualEnvs/AutoLens/lib/python3.6/site-packages/autofit/tools/phase.py", line 139, in run_analysis
>     return self.optimizer.fit(analysis, self.grid_priors)
>   File "/home/jammy/PyCharm/VirtualEnvs/AutoLens/lib/python3.6/site-packages/autofit/optimize/grid_search.py", line 145, in fit
>     arguments = self.make_arguments(values, grid_priors)
>   File "/home/jammy/PyCharm/VirtualEnvs/AutoLens/lib/python3.6/site-packages/autofit/optimize/grid_search.py", line 109, in make_arguments
>     if float("-inf") == grid_prior.lower_limit or float('inf') == grid_prior.upper_limit:
> AttributeError: 'Redshift' object has no attribute 'lower_limit'

**Comment by rhayes777** [comment]
This is because galaxy_model.redshift is a PriorModel not a Prior. galaxy_model.redshift.redshift will give you the underlying prior. I've illustrated this in an example under AutoLens/test/integration/grid_search/tests/redshift.py
