### ISSUE TITLE
Math and code modes

### ISSUE THREAD

**Issue by arm61** [rhayes777/PyAutoFit#124]
In the tutorials all code and math is written in the same font as the rest of the tutorial, it might benefit from the math mode and code mode that can be used in a jupyter notebook to improve clarity.

**Comment by Jammy2211** [comment]
Thank you so much for this suggestion - using code entries in the examples, tutorials, etc. make them sooooooooo much better :).

Covered most the project with this now, should pick up anything missing through general maintenance of the project!
