### ISSUE TITLE
Why not plot with error bars

### ISSUE THREAD

**Issue by arm61** [rhayes777/PyAutoFit#125]
In tutorial 2, you plot the gaussian `data` and `noise_map` separately. Is there a reason for this? (note I am not an astrophysicist so if this is standard in the community please tell me to bugger off.)

**Comment by Jammy2211** [comment]
Our history is in 2D image fitting, where plotting the noise map separate to the image is necessary. So I guess I just adopted that convention.

For users who's problems are 2D (or more) it'll be beneficial to keep the data and noise map them separate, but i agree for the 1D example including error bars on the plot will be visually more appeasing so will add such a plot!

**Comment by arm61** [comment]
Ahh right that does make sense though! I am a person from the world of fitting models to lines that all look very similar hence my thinking.

**Comment by Jammy2211** [comment]
Having added error bars to the plots, I agree they make the illustrations a lot easier to understand :).
