### ISSUE TITLE
How do I run tests?

### ISSUE THREAD

**Issue by arm61** [rhayes777/PyAutoFit#126]
For JOSS, I think there should be details of how I (the user) would run the tests if I were to install PyAutoFit from the source.

**Comment by Jammy2211** [comment]
Good shout, I've added instructions for installing from source (which include how to run tests) and a contibuting section to the github.

https://pyautofit.readthedocs.io/en/latest/general/installation.html#cloning-forking
https://github.com/rhayes777/PyAutoFit/blob/master/CONTRIBUTING.md
