### ISSUE TITLE
Default Prior Values for Parameters

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#130]
We've discussed how we intend to make all parameters have default values that are assumed if a config is not located.

We may need to change this for the default json config priors for parameters. Currentlly, if a parameters input on a class is something like param1 = 1.0, the default priors will be uniform priors between 0.0 and 1.0. Thus, if a user does not provide config files, all parameter priors will range 0.0 -> 1.0, which for most projects will lead to some very funky results.

I guess we should make the default inputs on each parameter something like param1 = UniformPriorDefault(value=1.0, lower_limit=0.0, upper_limit=1.0), or something with a nicer API...

We shoud also remove the dimensions / type mappings as they are just a pain in the arse and not really used.

**Comment by matthewghgriffiths** [comment]
Have you ever come across this [advice on prior choice](https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations)?

**Comment by Jammy2211** [comment]
Looks good, I'll give it a read tomorrow morning! 

The initial prior choices in AutoLens are definitely a bit... arbitrary and we should be aiming to make them more well informed. However, given how we fit things using pipelines that 'pass priors' via Gaussian priors, I don't think that changing these priors would actually have a meaningful impact on our final model inference and errors. It might finally be time to think more carefully about how we pass priors through a pipeline in a more statistically well defined sense (albeit may this is where the expectation propagation comes in).
