### ISSUE TITLE
Homogenize_aggregators method

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#132]
A problem we are running into is where we have, lets say, two aggregators, where their results are at different 'stages' so when we load the results they have a different number of datasets and results.

So, Agg_1 might have results corresponding to datasets 1,2 and 3, whereas Agg_2 might be datasets 1, 3, 4 and 5.

It'd be good if we could have a homogenize_aggregators method, which takes a list of aggregators and a property of theirs (the dataset name, a phase name filter, a directory_contains filter, etc) and returns the list such that all results not shared across all aggs are removed.

**Comment by rhayes777** [comment]
The intersection
