### ISSUE TITLE
Error when running welcome.py

### ISSUE THREAD

**Issue by karllark** [rhayes777/PyAutoFit#142]
There was an error when running the install instructions.  Below is a portion of the output showing the error that occurred when running `welcome.py`.

    backend=TKAgg
    backend=Qt5Agg
    backeknd=Qt4Agg

    [Press Enter to continue]
    
    Traceback (most recent call last):
     File "welcome.py", line 63, in <module>
       dataset_path = path.join("dataset", "example", "gaussian_x1")
     NameError: name 'path' is not defined

**Comment by Jammy2211** [comment]
Ah, there is a `from os import path` missing at the top of the welcome.py script. We did a big refactor to support Windows recently and I inserted that everywhere except there.

Could you add it manually and run the script? In the middle of a release so wary of pushing a fix myself currently.

**Comment by karllark** [comment]
That fixes the issue.  Moving on with `welcome.py`, there is a type.

"The reaming folders..." should be "The remaining folders...".

**Comment by Jammy2211** [comment]
Cheers, workspace was also spelled workpace :P.
