### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [rhayes777/PyAutoFit#154]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?
The interface should be very similar to dynesty.
UltraNest is a very reliable tuning-parameter-free algorithm. It can be faster than dynesty, especially if you take advantage of vectorization.
It also supports resuming from disk and MPI parallelisation, if that is useful to you.

**Comment by Jammy2211** [comment]
Absolutely! Adding support for UltraNest has been on my to-do list for a long time now, it's just adding new searches is an easy thing to push down in priority.

We've got a large refactor of the non linear module planned in the coming months and I'm planning to add new packages then, of which UltraNest will be one. I'll let you know when that finally happens 🙂.

Whilst you're here, we find that random walk nested sampling (in Dynesty) is extremely effective for strong lens modeling. We think that this is cause of parameter spaces are low enough N (< 20) and share high parameter covariance, which uniform sampling (Dynesty and MultiNest) struggles to capture. Does that sound at all reasonable to you and does UltraNest have a random walk sampler (or something similar you think it'd be worth us trying out for lens modeling).


p.s. sorry about the PyMultiNest typo, when I saw the GitHub post I had to double read your post to even see where exactly the typo was. I've updated the paper on GitHub but will have to see what the JOSS team say in terms of correcting the publication itself.

**Comment by JohannesBuchner** [comment]
Yes, there are a few step sampler implemented, and you can add custom ones.
tutorial: https://johannesbuchner.github.io/UltraNest/example-sine-highd.html 
API of that module: https://johannesbuchner.github.io/UltraNest/ultranest.html#module-ultranest.stepsampler

**Comment by Jammy2211** [comment]
Feature implemented, and will be included in the next release :)

Fingers crossed we can use this for strong lens modeling on HPC computers via MPI!

**Comment by JohannesBuchner** [comment]
Hurray!
