### ISSUE TITLE
Option in prior config for fixed

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#155]
We can set a UniformPrior as follows:

```
{
    "Gaussian": {
        "centre": {
            "type": "Uniform",
            "lower_limit": 0.0,
            "upper_limit": 100.0,
        }
}
```

Would be good to have an option where the default value is a fixed constant. This means one can write a Python class with additional parameters you may not fit for by default, but can make them model-components via customization if you so desire, e.g.:

```
{
    "Gaussian": {
        "centre": {
            "type": "Fixed",
            "value": 50.0,
        }
}
```

**Comment by rhayes777** [comment]
This already exists!

```json
{
    "Gaussian": {
        "centre": {
            "type": "Constant",
            "value": 50.0,
        }
}
