### ISSUE TITLE
Update database.py script to automatically write to .sqlite file

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#161]
I am writing a script on the database:

https://github.com/Jammy2211/autofit_workspace/blob/database/scripts/features/database.py

How do I make it so it automatically writes results to the .sqlite file, omitting the output paths? Or is this not support yet?

**Comment by rhayes777** [comment]
It should do it automatically as you add directories?

**Comment by Jammy2211** [comment]
Done.
