### ISSUE TITLE
By pass a need to make config file for priors, if all priors are manually specified

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#163]
Currently, if a .ini config file cannot be found for a class an error is raised.

However, there are use cases where one wants to quickly write a model, analysis class and fit it in a small self contained Python script. Its a pain have to worry about config files in the case.

Can we make it so the config check occurs when the `fit` function is called, so that a user can manually specify all priors before it is called? We also discussed having the Priors as part of a classes default parameters (e.g. how PyAutoFit uses these to know the number of parameters), but you werent keen due to it putting PyAutoFit in the API of the code outside PyAutoFit.

**Comment by rhayes777** [comment]
We'd need some kind of placeholder which might not be so pretty. Will have a think

**Comment by rhayes777** [comment]
Like a ConfigPromise
