### ISSUE TITLE
Nothing being written to output.log

### ISSUE THREAD

**Issue by jm22b** [rhayes777/PyAutoFit#17]
autofit v0.11.0
autolens v0.10.0

Nothing is being written to the output.log files during/after multinest runs.

The output section of my config file "general.ini" is:

[output]
log_interval = 50
log_file = output.log
number_of_accepted_samples_between_output = 10

**Comment by rhayes777** [comment]
I think this is because I moved configuration of logging from phase to non_linear. 

What specific logging is missing that you would expect to see?

**Comment by jm22b** [comment]
I would expect to see something like this:

"""
Running lens/source lens for... 

Lens Galaxy:
[Redshift: 1
Mass Profiles:
EllipticalIsothermal
centre: (-0.09137134281593623, 0.10504678016231356)
axis_ratio: 0.5760982852836021
phi: 82.05255070244695
einstein_radius: 1.719780361903838
slope: 2.0
core_radius: 0.0]

Source Galaxy:
[Redshift: 1
Pixelization:
shape: (30, 34)
Regularization:
<autolens.model.inversion.regularization.Constant object at 0x7f0b6a7b8080>]
"""

**Comment by rhayes777** [comment]
[general]
log_level = INFO

should be added to configuration
