### ISSUE TITLE
Continue a pipeline after a NLO grid search

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#19]
The NLO grid search works great!

We now have a need to continue a pipeline after the NLO grid search has run. Basically, we want the 'previous_results' of the next phase to have access to the models of the grid search. The most important result is the highest evidence model from the entire NLO search, so maybe something like

self.model = previous_results[-1].best_grid_search_model.variable.model

Having access to all grid search models (i.e. an index from 0 -> 35 for a 6 x 6 grid search) would be nice too, but not necessary.

**Comment by rhayes777** [comment]
The GridSearchResult class now implements best_result, best_model and all_models properties.

best_result returns the result with the highest figure of merit
best_model returns the ModelMapper instance associated with that result
all_models returns a list of all ModelMapper instances produced in the search
