### ISSUE TITLE
Using a session for the database after a run

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#193]
Lets say I perform some model-fits and have results on hard-disk (not using a session to write to the database).

If I then rerun those fits, but now with a session, could we make it so they add to the database (as if they had been run with a session)? This currently does not happen due to the completed feature, which skips most the calculation.

In general it would be nice to do runs not writing to the database (so results are on hard disk and easy to inspect) and then just piling them into the database as you move on to later fits.

**Comment by rhayes777** [comment]
It seems like this should be the default behaviour as the completed boolean in the database would initially be false?
