### ISSUE TITLE
model_mapper does not return PpriorLimitException, but Raises it

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#2]
In model mapper, this function: 

```
    def assert_within_limits(self, value):
        if not (self.lower_limit <= value <= self.upper_limit):
            raise exc.PriorLimitException(
                "The physical value {} for a prior was not within its limits {}, {}".format(value, self.lower_limit,
                                                                                            self.upper_limit))
```

Does not return the error. Thus, the error is not used in non_linear to resample a model outside the physical limits :(.

**Comment by rhayes777** [comment]
This is the correct behaviour

**Comment by Jammy2211** [comment]
When MultiNest runs it doesnt resample points though, it just constantly raises this error.

The other FitExceptions in the code return the errors to ensure that point is not included in the MultiNest samples.

**Comment by rhayes777** [comment]
0.4.3 resolves this issue. Exceptions raised creating model instances were not being caught so resampling did not occur.
