### ISSUE TITLE
Clean up optimizer grid search phase path / phase name

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#20]
I have made it so that in autofit, phase_name and phase_path are now separate. Previously, we used phase name to include the full directory structure of the output phase results (e.g. 'example_data/pipeline_name/phase_name'). 

This doesn't play nice with our use of named phase names to link previous results between pipelines, thus phase_path n ow takes the folers before the phase_name, e.g.:

phase_path = 'example_data/pipeline_name/
phase_name='phase_name'.

Implementing this throughout autofit was straight forward, however I wasnt able to get the optimizer_grid_search to do it properly. Specifically, at line 167, the phase of each optimizer grid search is still setup using:

```
            name_path = "{}/{}".format(self.phase_name, "_".join(labels))
            optimizer_instance = self.optimizer_class(model_mapper=model_mapper,
                                                      phase_path='', phase_name=name_path)
```

That is, the path is setup using the full phase name as it was before. This passes all tests, but doesnt mesh nicely with the new layout. Iff you can get this input to use phase path as per usual we're good.

**Comment by Jammy2211** [comment]
I think I have fixed this, but you shouold probably check before we close the issue.

It lookss like all integration tests behave as expected.

**Comment by rhayes777** [comment]
Looks fine to me
