### ISSUE TITLE
Add Starting Point result passing

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#201]
Prior passing passes a result as a GaussianPrior, where the mean and sigma are set via config files.

We should add a new type of model passing result, something like `result.start` which passes the result as a StartingPoint object described in issue https://github.com/rhayes777/PyAutoFit/issues/200

**Comment by rhayes777** [comment]
Is this not the same as the centre of the posterior/prior?

**Comment by Jammy2211** [comment]
It isn't a single optimizer, it'll be used by all MCMC methods, the Particle Swarm and I would guess most Scipy codes. Its only nested sampling this wouldn't be applicable for.

I think that whether or not a parameter has a `StartPoint` it'll always have a `Prior` regardless. Maybe it belongs in the `initializer.py` module?

**Comment by rhayes777** [comment]
It seems sensible then to put it in a Prior. If it's not present the Prior can simply default to the median value.

**Comment by Jammy2211** [comment]
Indeed, we should also have a bool in a Search that by default disables start points but if set to True enables them (so I can manually set it to true in every MCMC, Optimizer, etc.). This will ensure an exception is raised whenever a Nested sampler has a StartPoint passed to it.
