### ISSUE TITLE
Choose sym link path

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#22]
Currntly, the sym link goes to the $HOME folder, if not specified otherwise.

On the supercomputer, this puts it in the home directory of the user, whiich has limited hard disk space, thus filling the folder up with multinest files.

We use the $HOME environmental variable to setup the runs before submitting them to the supercomputer, so we cant overwrite $HOME to choose our sym link path.

Could we get an option in the config file that speciies the path? E.g. if its HOME it uses home, but can also be a directory path.

**Comment by rhayes777** [comment]
you can now set:

export SYMDIR="/path/to/.autolens"

To use a different path.
