### ISSUE TITLE
variable link via absolute or relative value within pipeline

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#23]
Currently, we link two parameters as

param = results.from_phase('phase').variable

The width of the Gaussian prior that makes this link is set by the width config file. It'd be nice if we could set this width manually in the link, for super customized pipelines. For example.

param = results.from_phase('phase').variable_absolute(a=1.0)
param = results.from_phase('phase').variable_relative(r=0.5)

**Comment by rhayes777** [comment]
This has been implemented with the exact usage specified above.
