### ISSUE TITLE
Use NLO pickle to ensure resumes are identical state

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#24]
If a MultiNest run is resumed, and any of the following are changed:

- The model.
- The priors on the model.
- The NLO settings.

We should raise an error so that the run does not resume. Now we are pickling the NLO, we can do exactly that.

**Comment by rhayes777** [comment]
The pipeline now asserts that, if a pickle file already exists, the optimiser loaded from the pickle is equal to the optimiser of the phase. If they are not equal then a PipelineException is raised.

Equality means dictionary equality between the two optimisers. This includes optimiser paths which may cause an issue if files are moved. Equality between the model mapper and its children accounts for equality in prior models and their priors.
