### ISSUE TITLE
Make it so two parameters have a shared relative offset

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#246]
In strong lensing, we might have two galaxies where we know their centres are offset by a certain amount, e.g. (0.0, 0.0) and (0.1, 0.1).

I've had requests to make it possible to compose a model where the centres are aligned, but with this offset. E.g:

lens_0.centre_0 = lens_1.centre_0 + 0.1
lens_0.centre_1 = lens_1.centre_1 + 0.1

I assume this is not possible with the current autofit, but it would be a usual thing to add to model composition.

**Comment by rhayes777** [comment]
Actually I think that should already work?

**Comment by rhayes777** [comment]
Yeah this is already implemented:

```
    def test_prior_plus_float(self, prior):
        sum_prior = prior + 1.0
        assert sum_prior.instance_from_unit_vector([1.0]) == 2.0

    def test_float_plus_prior(self, prior):
        sum_prior = 1.0 + prior
        assert sum_prior.instance_from_unit_vector([1.0]) == 2.0
