### ISSUE TITLE
Unique id does not distinguish UniformPrior and LogUniformPrior

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#251]
I think these give the same unique id:

```
gaussian_0 = af.Model(p.Gaussian)
gaussian_0.intensity = af.UniformPrior(lower_limit=1e-6, upper_limit=1e6)
```

```
gaussian_0 = af.Model(p.Gaussian)
gaussian_0.intensity = af.LogUniformPrior(lower_limit=1e-6, upper_limit=1e6)
```

Backwards compatibility is gonna be...interesting :P

**Comment by rhayes777** [comment]
Haha yeah unfortunately we're going to keep trashing your previous ids until we've ironed out all the bugs...

**Comment by Jammy2211** [comment]
Could we add a `old_unique_id` bool to the config and put it on this clause?

I'm not in a position to rerun a load of results currently, so this is probably the best we can do.

**Comment by rhayes777** [comment]
Ha it's in danger of getting ugly but I'll put it in

**Comment by Jammy2211** [comment]
I'll aim for us to remove it asap but I suspect other issues will crop up (see https://github.com/rhayes777/PyAutoFit/issues/244) so a 'freezing' of ids is probably a necessitiy whilst I do science.

**Comment by rhayes777** [comment]
I'll version them

**Comment by rhayes777** [comment]
so now you can set the identifier version in general.ini

1 is before this change, 2 is after
