### ISSUE TITLE
Example of graphical model fit (no expectation propogation) gives terrible results

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#252]
The following script fits 3 gaussians correctly:

`https://github.com/Jammy2211/autofit_workspace/blob/master/scripts/howtofit/chapter_graphical_models/tutorial_1_global_model.py`

The following script uses a FactorModel to do this and gives terrible resutls:

`https://github.com/Jammy2211/autofit_workspace/blob/master/scripts/howtofit/chapter_graphical_models/tutorial_2_graphical_model.py`

The results using expectation propogation look ok though (the script crashes due to another problem, but the first fit is OK:

`https://github.com/Jammy2211/autofit_workspace/blob/master/scripts/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation.py`

So, I think there is an issue with the use of the `global_prior_model` or how I am setting up the global fit:

```
factor_graph = g.FactorGraphModel(model_factor_0, model_factor_1, model_factor_2)

search = af.DynestyStatic(
    path_prefix=path.join("howtofit", "chapter_graphical_models"),
    name="tutorial_2_graphical_model",
    sample="rwalk",
)

result = search.fit(model=factor_graph.global_prior_model, analysis=factor_graph)
```

I'm a bit skeptical of the  **analysis=factor_graph** (I couldn't see a global analysis property).

**Comment by rhayes777** [comment]
Could the way we compute loglikelihood be the problem? I'm guessing it ought to be summed.

This is in autofit/graphical/declarative/collection.py

```python
def log_likelihood_function(
            self,
            instance: ModelInstance
    ) -> float:
        """
        Compute the combined likelihood of each factor from a collection of instances
        with the same ordering as the factors.

        Parameters
        ----------
        instance
            A collection of instances, one corresponding to each factor

        Returns
        -------
        The combined likelihood of all factors
        """
        likelihood = abs(
            self.model_factors[0].log_likelihood_function(
                instance[0]
            )
        )
        for model_factor, instance_ in zip(
                self.model_factors[1:],
                instance[1:]
        ):
            likelihood *= abs(
                model_factor.log_likelihood_function(
                    instance_
                )
            )
        return -likelihood

**Comment by rhayes777** [comment]
I guess it's also possible that the lists of model factors and models get mismatched?

**Comment by Jammy2211** [comment]
Fixed.
