### ISSUE TITLE
Automated EDEN project building

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#259]
I found out that EDEN projects support nested Python modules... who knew.

So, this should provide us with an extremely elegent way to build eden projects. I will illustrate this with an example, whereby we will build the `autofit.mapper` package in the corresponding `VIS_CTI` project.

**Building the project:**

The `autofit.mapper` package is structured as follows:

```
autofit

   > mapper

       >prior
       >prior_model
```

We want to map this to the `VIS_CTI` project with the following structure:

```
VIS_CTI

     > VIS_CTI_Fit (<-> autofit)

            > python

                    > VIS_CTI_Fit (<-> autofit)

                              > VIS_CTI_Fit_Mapper (<- >mapper)

                                        > VIS_CTI_Fit_Prior (<- >prior)
                                        > VIS_CTI_Fit_PriorModel (<- >prior_model)
```

We could build the above project from the following two config files:

```
autofit=VIS_CTI_Fit
```

```
mapper=VIS_CTI_Fit_Mapper
prior=VIS_CTI_Fit_Prior
prior_model=VIS_CTI_Fit_PriorModel
```

The process is fairly simple, we load the project name `autofit`, create the `VIS_CTI_Fit` folders and from there create `VIS_CTI_Fit_Mapper` with its sub packages. In fact, the `VIS_CTI_Fit` package will already exist, as it contains files specific to EDEN that do not change.

When we make each of the `VIS_CTI_` packages, we copy all the python files / folders from the `autofit` project to the `VIS_CTI_Fit` part.

This can then be generalized over all projects.

**Imports**

At the same time, we need to rename all project imports, with the pattern as follows:

`from autofit.mapper.prior_model.collection import CollectionPriorModel`
`from VIS_CTI_Fit.VIS_CTI_Fit_Mapper.VIS_CTI_Fit_PriorModel.collection import CollectionPriorModel`

**Tests**

Tests are stored in the following folder:

```
VIS_CTI

     > VIS_CTI_Fit (<-> autofit)

            > python

                    > VIS_CTI_Fit (<-> autofit)

                              ....

       > tests

                 >python

                            test_something.py
                            test_something_else.py
```

In classic EDEN fashion, the tests folder does not support nested folders. So we'll need to dump every unit test in there in one giant mega module.

Could you write a Python script (or bash if you prefer) that does the project build + import rename? The symmetry and pattern looks pretty clean so fingers crossed its straight forward from here!

**Comment by rhayes777** [comment]
This step is now performed after this existing edenise step by the same script.

Two new fields are defined in the eden.ini
```
[eden]
name = autofit
prefix = af
eden_prefix = VIS_CTI  # The prefix for all imports
eden_dependencies = autoconf  # Comma separated list of other projects that are edenised on which this project depends

**Comment by Jammy2211** [comment]
Issues:

- The names of modules being imported which are at the most outer part of a package are still being changed, for example:
 `from VIS_CTI_Autofit.VIS_CTI_NonLinear.VIS_CTI_Samples`

should be

`from VIS_CTI_Autofit.VIS_CTI_NonLinear.samples`

In fact, I am unclear on the pattern of why certain things are being renamed and not others). I would guess theres an obvious bit of the code you didnt apply the bool to.

**Comment by rhayes777** [comment]
Should be resolved by latest PR. Also spotted another issue where it doesn't deal well with unbalanced parentheses in a docstring.

If we're not careful I'm going to end up writing a compiler...

**Comment by Jammy2211** [comment]
Two new issues:

1) The following import in autoarray / autofit: `from autoconf import conf` is not being renamed to: `from VIS_CTI_Autoconf import conf`. (it is instead `from VIS_CTI_Autoarray import conf`. A similar issues occurs where 

`from autoconf.exc import ConfigException, PriorException` is renamed to `from VIS_CTI_Autofit.exc import ConfigException, PriorException` and not `from VIS_CTI_Autoconf.exc import ConfigException, PriorException`

2) Brackets still cause issues in docstrings, specifically when a bracket opens or closes on a line without a corresponding shut bracket. This typically means the code fails to convert at he final docstring.
