### ISSUE TITLE
Automatically delete optimizer folder in phase when resuming a job

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#29]
When I downlad the results from a super computer  iget a set of optimizr folders which are empty (their sim link doesnt point to a al location on my laptop).

We created a scheme where the optimizer_backup folder would overwrite these folders, so that jobs could be restarted from the laptop. However, this crashes before the overwrite happens, as the optimizer folder exists.

Can we make it so that the optimizer folder is delete (or over written) when a pipeline starts in this way.

**Comment by rhayes777** [comment]
So if the optimiser folder is a dead symlink then it should be removed?

**Comment by Jammy2211** [comment]
Yeah, something like that

**Comment by Jammy2211** [comment]
Think everything is behaving as desired now.

Going to close, but we should aim to get some integration tests w/ assertions for this.
