### ISSUE TITLE
Backup path now used for all MultliNest NLO output

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#30]
The opt_path was used to load the MultiNest summary / weighted samples files. This meant that when I opened a pickled instance of a MultiNest class from the super computed, I could not load these files as the path point to a sym-link.

I have it so that the back_up path is now used for everything, as this is a Python string and thus works regardless of sym-link. This, the opt_path and sym_link are now only used during a MultiNest fit, whcih I think is what we want.

A consequence of me doing this is that the self.backup() function that runs at the end of every NLO (MultiNest, DHS, Grid) moved up a few lines to happen befores results were output and visualized. This ensures the necessary files are present in the optimizer_backup folder before they are used for output.

**Comment by rhayes777** [comment]
I think we should try to separate out the name of a phase from the rest of the path, so it can be reconstructed in any environment by swapping out the rest of the path for the new location in which it is found

**Comment by rhayes777** [comment]
Restore is now called when an object is deserialised by pickle. This means that the symlinked folder should now be available (as a copy of backup). I'd recommend reverting to using the actual folder rather than the backup for visualisation etc.
