### ISSUE TITLE
Fast access results

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#307]
The maximum log likelhood instance is stored in the database and can be accessed directly as follows:

`aggregator[0].instance`

All other results are currently only accessible via a `aggregator.values("samples")`, which can be slow because it has to unpack the Samples pickle. We should therefore add more fast access results, I suggest the following:

`aggregator[0].max_log_likelihood_instance` ( this is just a rename of the code above, to be more explicit)
`aggregator[0].median_pdf_instance`
`aggregator[0].max_log_posterior_instance`
`aggregator[0].instance_at_3_upper_sigma` (corresponds to `Samples.instance_at_upper_sigma(sigma=3.0)`)
`aggregator[0].instance_at_2_upper_sigma` 
`aggregator[0].instance_at_1_upper_sigma` 
`aggregator[0].instance_at_3_lower_sigma` 
`aggregator[0].instance_at_2_lower_sigma` 
`aggregator[0].instance_at_1_lower_sigma` 
`aggregator[0].error_instance_at_3_upper_sigma` (corresponds to `Samples.error_instance_at_upper_sigma(sigma=3.0)`)
`aggregator[0].error_instance_at_2_upper_sigma`
`aggregator[0].error_instance_at_1_upper_sigma`
`aggregator[0].error_instance_at_3_lower_sigma`
`aggregator[0].error_instance_at_2_lower_sigma`
`aggregator[0].error_instance_at_1_lower_sigma`

If there is any reason storing lots of these is a bad idea let me know and we can maybe compress it down, or something.

**Comment by rhayes777** [comment]
Yeah we can do this. I wonder if it's worth while/possible to use a string naming strategy instead like aggregator[0].instance_dict['some instance']

**Comment by Jammy2211** [comment]
I agree, albeit maybe something like aggregator[0].fast("max_log_likelihood_instance")
