### ISSUE TITLE
How often do IntervalCounters count?

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#31]
For visualization, back-up and logging, we IntervalCounters, which then perform the task depending on the config values:

```
    class Fitness(object):
        
        def __init__(self, nlo, analysis, image_path):

            self.nlo = nlo
            self.result = None
            self.max_likelihood = -np.inf
            self.image_path = image_path
            self.analysis = analysis
            visualise_interval = conf.instance.general.get('output', 'visualise_interval', int)
            log_interval = conf.instance.general.get('output', 'log_interval', int)
            backup_interval = conf.instance.general.get('output', 'backup_interval', int)

            self.should_log = IntervalCounter(log_interval)
            self.should_visualise = IntervalCounter(visualise_interval)
            self.should_backup = IntervalCounter(backup_interval)

        def fit_instance(self, instance):
            likelihood = self.analysis.fit(instance)

            if likelihood > self.max_likelihood:
                self.max_likelihood = likelihood
                self.result = Result(instance, likelihood)

                if self.should_visualise():
                    self.analysis.visualize(instance, image_path=self.image_path, during_analysis=True)

            if self.should_backup():
                self.nlo.backup()

            return likelihood
```

My question is, do these counts add 1 every time an **accepted** sample (e.g. it inceases the likelihood) is made, or just for every single model called in fit_instance?

If it is the latter, I think that we should change it to the former, as it is leading to a large amount of backups / logs to take place, which hurts us due to high IO on the super computer. If it isn't the latter, then it means something else is slowing down our super computer runs...

**Comment by Jammy2211** [comment]
Looking at the above code, my guess is that we want to move the if self.should_back() clause to the right, to align with the should_visualise.

**Comment by rhayes777** [comment]
Yes if you only want backups to occur when the model improves that's true.
