### ISSUE TITLE
Sensitivty Mapping paths wrong

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#359]
Here is the paths of sensitivty mapping performed with autolens:

![image](https://user-images.githubusercontent.com/23455639/136989274-ab4355a9-dcb3-4901-8c4f-3252a4df79f2.png)

Here is the search used for sensitviity mapping:

```
    search = af.DynestyStatic(
        path_prefix="slacs",
        name="subhalo__sensitivity",
        unique_tag="lens_0",
        number_of_cores=settings_autofit.number_of_cores,
        session=settings_autofit.session,
        nlive=100,
    )

```
Clearly, the path prefix, unique tag and name are not being used to locate the results in the same folder as the other results shown in the image.

It should be that the folders `[base]` and `[perturbed]` and in the same folder as folders like `light[1]_light[parametric]`.

**Comment by Jammy2211** [comment]
Furthemore, the same unique identifiers are always generated for [base] and [perturber]:

![image](https://user-images.githubusercontent.com/23455639/136999926-c0c8ff26-6e52-42c6-bc8f-81deaefe2927.png)

This is the expected behaviour, as the model being fitted in both cases is identical and it is only ther dataset that is fitted that changes (which is simulated in the `simulate_function` of the `Sensitivity` class. 

I think we have this previously and that is has been lost in these path issues, but we need results to go in the folder describing the name of the simulation, which is what occurs for a SearchGridSearch:

![image](https://user-images.githubusercontent.com/23455639/137000226-9298d09b-0459-4722-8d21-e88405dd6c54.png)

**Comment by rhayes777** [comment]
I think this is resolved
