### ISSUE TITLE
model.info files are screwed

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#36]
Here is a model.info file from AutoLens:

```
CollectionPriorModel

lens_galaxies_GalaxyModel

lens_galaxies_lens_EllipticalIsothermal

lens_galaxies_lens_mass_axis_ratio                                                  UniformPrior, lower_limit = 0.2, upper_limit = 1.0
lens_galaxies_lens_mass_phi                                                         UniformPrior, lower_limit = 0.0, upper_limit = 180.0
lens_galaxies_lens_mass_Length

lens_galaxies_lens_mass_einstein_radius_value                                                       UniformPrior, lower_limit = 0.0, upper_limit = 4.0

CollectionPriorModel

source_galaxies_GalaxyModel

source_galaxies_source_EllipticalSersic

source_galaxies_source_light_axis_ratio                                                  UniformPrior, lower_limit = 0.2, upper_limit = 1.0
source_galaxies_source_light_phi                                                         UniformPrior, lower_limit = 0.0, upper_limit = 180.0
source_galaxies_source_light_sersic_index                                                UniformPrior, lower_limit = 0.8, upper_limit = 8.0
source_galaxies_source_light_Luminosity

source_galaxies_source_light_intensity_value                                                       LogUniformPrior, lower_limit = 1e-06, upper_limit = 10.0
source_galaxies_source_light_Length

source_galaxies_source_light_effective_radius_value                                                       UniformPrior, lower_limit = 0.0, upper_limit = 4.0
```

After you went on holiday we managed to screw these up somehow. Prob not too tricky to fix.

**Comment by rhayes777** [comment]
I've redone how model results work. The hierarchy is now represented by titles for objects and indented sections. Included in this work is the removal of constants, which are now just floats.

Here's an example:
`
lens_galaxies
    lens
        mass
            centre
                centre_0                                      GaussianPrior, mean = 0.0, sigma = 0.3
                centre_1                                      GaussianPrior, mean = 0.0, sigma = 0.3
            axis_ratio                            UniformPrior, lower_limit = 0.2, upper_limit = 1.0
            phi                                 UniformPrior, lower_limit = 0.0, upper_limit = 180.0
            einstein_radius                       UniformPrior, lower_limit = 0.0, upper_limit = 4.0
        redshift                                                                                 0.5
source_galaxies
    source_0
        sersic
            centre
                centre_0                                      GaussianPrior, mean = 0.0, sigma = 0.3
                centre_1                                      GaussianPrior, mean = 0.0, sigma = 0.3
            axis_ratio                            UniformPrior, lower_limit = 0.2, upper_limit = 1.0
            phi                                 UniformPrior, lower_limit = 0.0, upper_limit = 180.0
            intensity                       LogUniformPrior, lower_limit = 1e-06, upper_limit = 10.0
            effective_radius                      UniformPrior, lower_limit = 0.0, upper_limit = 4.0
            sersic_index                          UniformPrior, lower_limit = 0.8, upper_limit = 8.0
        redshift                                                                                 1.0
`

**Comment by rhayes777** [comment]
Indenting doesn't seem to work in the example.

**Comment by rhayes777** [comment]
Also note that only floats work as constants. Integers are not accounted for because they have other uses in the model and all real physical values are representable as floats.
