### ISSUE TITLE
Aggregator With Tag

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#38]
Once I add pipeline tagging to the code, the directory structure of a fit will be as follows:

```
-> Pipeline_1
   -> Pipeline_Tag__Does_Something_Cool
        -> Phase_1_Fit
            ->Phase_Tag__Sub_1
            -> Phase_Tag__Sub_2
        -> Phase_2_Another_Fit
            -> Phase_Tag__Sub_1
    -> Pipeline_Tag__Does_Something_Else_Cool
        -> Phase_1_Fit
            -> Phase_Tag__Sub_2
        -> Phase_2_Another_Fit
            -> Phase_Tag__Sub_1
-> Pipeline_2
   -> Pipeline_Tag__Does_Something_Cool
        -> Phase_1_Fit
            ->Phase_Tag__Sub_1
```

So, what we want with the aggregator is the ability to grab  whatever results we want from this path structure. So, in the simplest case, we could supply all 4 strings:

pipeline_name = 'Pipeline_1'
pipeline_tag = 'Pipeline_Tag__Does_Something_Cool'
phase_name = 'Phase_2_Another_Fit
phase_tag = 'Phase_Tag__Sub_1'

This will get the results of all images which are fitted with that specific set of pipelines, tags, phases, etc.

Next, lets say we don't specify a phase tag. What should the aggregator do? For each image, it should retrieve all fits using the input pipeline_name, pipeline_tag and phase_name. Thus, for each image it should retrieve a list of fits, one for each phase_tag in the Phase_Name folder.

If a pipeline_tag isn't specified it should do the same. That is, for every image, it should retrieve a list for all of the different pipelines it was run on, given the phase_name and phase_tag which specify which folder to look in.

I guess if pipeline_tag and phase_tag are missing, we'll have list of lists.

Should the agggregator by default return lists of lists of lists? e.g.

optimizers = aggregator.opt_from_what

optimizers[pipeline_tag_index]][phase_tag_index]

**Comment by Jammy2211** [comment]
Alternatively, to avoid lists of lists we could just require that if there are multiple pipelines, tags, phases, etc. The user has to specify them all. Then, in the script itself the user can create the optimizers lists they want, e.g.

optimizers_pipeline_tag_1 = aggregator.opt_from_what(pipeline_name='', pipeline_tag='tag_1')
optimizers_pipeline_tag_2 = aggregator.opt_from_what(pipeline_name='', pipeline_tag='tag_2')

This might be better.

**Comment by rhayes777** [comment]
I've added phase tags to the metadata

**Comment by rhayes777** [comment]
Phase and Aggregator tags are now stored in the metadata
