### ISSUE TITLE
Backup results in a non-sim link directory.

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#4]
It is common for 'ungraceful exits' to make the MultiNest results unresumeable. It is also a pain having the results in a sim-link directory (especially in docker, where this cant be accessed).

I think it would be wise to copy all results in a strategic way to a non-sim link folder (e.g. optimizer_backup) so that they can be accessed there, and used to resume a run if the sim-link results are corrupted.

**Comment by rhayes777** [comment]
As of 0.4.0 an optimizer_backup folder will be created and overwritten in the output folder at an interval, backup_interval, defined in general.ini
