### ISSUE TITLE
model.info files missing for graphical model factors / optimizations

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#428]
I performed an EP fit using the script:

https://github.com/Jammy2211/autofit_workspace/blob/release/scripts/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation.py

Here are my output folders:

![image](https://user-images.githubusercontent.com/23455639/144297769-4c460b7f-8dca-44b4-a1b3-9fea9b4f6089.png)

The factor optimizations are missing the `model.info` files, which would indicate how the priors are updated fit-by-fit.

**Comment by rhayes777** [comment]
These appear for me when I run this test
