### ISSUE TITLE
Don't resume a MultiNest run if model.results exists

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#44]
Getting a fairly dodgy issue - MultiNest runs are resuming even after they have finished in a previous run (e.g. once they've made a model.results file). Not totally sure of the cause of this, I guess MultiNest has some randomness as to whether it decides it should finish or not.

This is problematic, as if MultiNest resumes a run that it previously continued beyond, then it will change the priors / hyper image / etc of the subsquent run, which can really mess things up.

I think a good solutoin to prevent this from happening from now is to simply check if a model.results file exists, and if so, to not start MultiNest.

We may also benefit from introducing some sort of check pointing, so a run 'resumes' from exactly where it left off in a pipeline. This could be a nightmare with passing / loading data though...

**Comment by rhayes777** [comment]
I thought multinest handled this itself by checking whether mutlinest generated files were present?

**Comment by Jammy2211** [comment]
MulitNest loads up the entire set of results as if its going to resume. It then re-analyses them to determine if its finishing criteria has been met. This should always produce the same result and prevent MultiNest from restarting, but it appears that isnt always the case.

Because we load all results manually for pipeline information passing it shouldnt matter if we skip a MultiNest run.

**Comment by rhayes777** [comment]
Presumably the new completed-skip mechanism means this is no longer necessary?

**Comment by Jammy2211** [comment]
yep
