### ISSUE TITLE
assert_within_prior_limits decorator

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#442]
This decorator has caused issues, whereby it now asserts whether the parameters are within the parameters on more function calls than it did previously.

For dynesty (and other searches) this is problematic, because it now does so on the function `vector_from_unit_vector`, which is called when mapping unit values to physical values.

Previously, this did not have assert prior limits called on it, meaning that the follow function always ran regardless:

```
def prior_transform(cube, model):

    phys_cube = model.vector_from_unit_vector(unit_vector=cube)

    for i in range(len(phys_cube)):
        cube[i] = phys_cube[i]

    return cube
```

If a model was outside the prior limits, it wss not until later in the log likelihood function call when the log likelihood was computed that assert prior limits was called:

```
        def log_likelihood_from(self, parameter_list):

            instance = self.model.instance_from_vector(vector=parameter_list)
            log_likelihood = self.fit_instance(instance)

            return log_likelihood
```

The function `instance_from_vector` did the assert prior check.

The key difference between the two is when the exception is raised on the log likelihood, I can return a really small value (e.g. `-1.0e99) to negate the model and have Dynesty ignore it. I cannot do an equivalent step with the `phys_cube` without crashing Dynesty.

Because this interacts with the internal of search libraries, there is no straight forward way to remedy this with a try / except clause.

I think we need every function that the decorator calls to have the `assert_within_prior_limits` bool.

**Comment by rhayes777** [comment]
You can set ignore_prior_limits=True when calling vector_from_unit_vector

**Comment by Jammy2211** [comment]
Didnt your PR before xmas sort this?

**Comment by rhayes777** [comment]
Yeah I guess we forgot to close it
