### ISSUE TITLE
Ordering of parameters via paths

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#455]
In this issue we implemented filtering via paths:

https://github.com/rhayes777/PyAutoFit/issues/450

e.g.:

```
samples = samples.with_paths(
    [
        ("galaxies", "lens", "mass"),
        ("galaxies", "lens", "shear"),
    ]
)
```

I think it would be good to have an equivalent method for ordering the internal parameters of the model and `Samples` object via the same API, e.g.:

```
samples = samples.order_front(
    [
        ("galaxies", "lens", "mass", "centre_0"),
        ("galaxies", "lens", "mass", "einstein_radius"),
    ]
)
```

In the above example, the parameters `mass.centre_0` and then `einstein_radius` would be moved to the front of the internal model ordering (e.g. they would be indexes 0 and 1 in lists used by the model).

The reason to implement this is that when using a model to output results to Latex tables and make certain visualizations, currently the ordering of the results can be somewhat unintuitive and not suitable for putting in a paper. This would give us the tools we need to reorder results when I'm writing a paper.

**Comment by Jammy2211** [comment]
Note also there is an issue for filtering with the specification of tuple parameters:

https://github.com/rhayes777/PyAutoFit/issues/450

**Comment by rhayes777** [comment]
I'm not sure about this. Making the model emit paths in a specific order would require changing the ids of the priors. Is it that difficult to change the other of data once you've already taken it out of the samples object?

**Comment by Jammy2211** [comment]
The difficulty is once we change the model order we need to be sure it is reflected everywhere, as this ordering is used when the samples are used for visualization, to make latex tables. We could implement ordering when these things occur, but we may end up with other occurances  where order matters leading to a lot of repetition.

The `Samples` model attribute is used for a fairly scarse amount of things:

`self.model.instance_from_vector`
`self.model.all_paths`
`self.model.all_names`
`self.model.model_component_and_parameter_names`
`self.model.prior_count`

Would it be possible to create a separate `ModelMapper` class which is passed to `Samples`, which removes functionality like ids giving us more freedom to do things like change its order? Feels like a lot of code complexity though...
