### ISSUE TITLE
Attributes of hyper combined phase need to default to None

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#46]
If I run a pipeline with all hyper-mode features off, e.g.:

```
    phase1 = phase1.extend_with_multiple_hyper_phases(
        hyper_galaxy=False,
        include_background_sky=False,
        include_background_noise=False,
    )
```

This will not produced a 'hyper_combined' phase. We typically use this phase to setup these parts of the model in the next phase:

```
    phase2 = al.PhaseImaging(
        phase_name="phase_2__lens_sie__source_sersic",
        phase_folders=phase_folders,
        galaxies=dict(
            lens=al.GalaxyModel(
                redshift=redshift_lens,
                bulge=phase1.result.instance.galaxies.lens.bulge,
                disk=phase1.result.instance.galaxies.lens.disk,
                mass=mass,
                shear=shear,
                hyper_galaxy=phase1.result.hyper_combined.instance.galaxies.lens.hyper_galaxy,
            ),
            source=al.GalaxyModel(
                redshift=redshift_source, light=al.lp.EllipticalSersic
            ),
        ),
        hyper_image_sky=phase1.result.hyper_combined.instance.hyper_image_sky,
        hyper_background_noise=phase1.result.hyper_combined.instance.hyper_background_noise,
        sub_size=sub_size,
        signal_to_noise_limit=signal_to_noise_limit,
        bin_up_factor=bin_up_factor,
        positions_threshold=positions_threshold,
        inner_mask_radii=inner_mask_radii,
        pixel_scale_interpolation_grid=pixel_scale_interpolation_grid,
        optimizer_class=af.MultiNest,
    )
```

Hyper pipelines take optional inputs to determine if these features are used or not, so having them all "False" is a plausible run one could do. Would it be possible to make it so if a hyper phase doesn't run, using result.hyper_combined will always return a None irrespective of the attribute access?

This is currently leaidng to a bug in the pipeline where an infinite recursion error is raised, presumeably because it cannot find the relevent hyper parameters.

**Comment by rhayes777** [comment]
You can now specify a promise as optional.

af.last.model.optional.path.to.item

Instead of raising an error on population a None is returned when no object is found
