### ISSUE TITLE
Raise error is 'result.model' or 'result.instance' is not called

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#48]
I had a pipeline with a typo, which setup a prior as light=phase1.result.variale.galaxies.lens.light'. This didn't raise an error, but intead lead to an infnite loop in the recursion (the error was thatt he recusion infinite loop was hit).

We should make sure typos are flagged.

**Comment by rhayes777** [comment]
The problem here is that we use result.hyper where hyper could have any name. We could change the syntax so that getting hyper results involves calling some function but that would be a change to the API

**Comment by Jammy2211** [comment]
Leave the API so just hope there are no typos.
