### ISSUE TITLE
Outdated Jupyter Notebook tutorial.

### ISSUE THREAD

**Issue by VictorForouhar** [rhayes777/PyAutoFit#488]
## Enviroment
I am using the Binder enviroment provided with the HowToFit lectures.

## Code
I am using the notebook provided for Tutorial 3 (Expectation propagation) of the Graphical Model fitting. 

## Error
Cell 9 defines a Laplace optimiser via:
>laplace = g.LaplaceFactorOptimiser(transform_cls=DiagonalMatrix)

However, when I run this cell, it returns the following error message:
>AttributeError: module 'autofit.graphical' has no attribute 'LaplaceFactorOptimiser'

I am able to circumvent this error message in two ways. One is changing this line to:
>laplace = g.LaplaceOptimiser()

However, the parameter *transform_cls* is no longer recognised. Another way is using:
> from autofit.graphical.optimise import LaplaceFactorOptimiser
> laplace = LaplaceFactorOptimiser(transform_cls=DiagonalMatrix)

This is similar to the original code in the cell. Which one should I use?

**Comment by Jammy2211** [comment]
Ooops, looks like we removed it from the imports when doing a refactor.

The following code will sort this:

```
from autofit.graphical.optimise import LaplaceFactorOptimiser

laplace = LaplaceFactorOptimiser(transform_cls=DiagonalMatrix)
```

The tutorial runs fine for me with this edit.

**Comment by VictorForouhar** [comment]
Thank you! However, when I make this change I get an error regarding the number of values to unpack:

```
2022-03-13 13:14:59,550 - autofit.graphical.expectation_propagation.optimiser - ERROR - too many values to unpack (expected 3)
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/graphical/expectation_propagation/optimiser.py", line 236, in run
    model_approx,
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/graphical/optimise.py", line 289, in optimise
    res = opt.maximise(start, status=status, **opt_kws)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/graphical/optimise.py", line 223, in maximise
    return self._parse_result(res, status=status)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/graphical/optimise.py", line 162, in _parse_result
    success, messages, flag = status
ValueError: too many values to unpack (expected 3)
```
Additionally, I also get an exception regarding the priors once all the datasets have each been optimised for the first time:
```
PriorLimitException: The physical value -1.9371047829447752 for a prior was not within its limits 0.0, inf
```

I originally thought this was due to the default Gaussian priors for the normalisation and standard deviation of the Gaussians to fit, but I then saw that a lower limit of 0 is imposed. In any case, the problem stems from fitting dataset_1, which somehow yields negative normalisations and standard deviations. For this example, the model.results reads:

> Maximum Log Likelihood Model:
> 
> centre                                                                                    80.431
> normalization                                                                             0.155
> sigma                                                                                     -0.834
> 
> Summary (3.0 sigma limits):
> 
> centre                                                                                    54.01 (20.65, 79.96)
> normalization                                                                             0.19 (-4.81, 8.62)
> sigma                                                                                     11.10 (-23.66, 31.86)
> 
> 
> Summary (1.0 sigma limits):
> 
> centre                                                                                    54.01 (43.85, 63.38)
> normalization                                                                             0.19 (-0.11, 0.53)
> sigma                                                                                     11.10 (2.74, 21.69)
> 

I presume this particular exception comes from updating the priors for the second round of optimisation, which yields negative values due to using dataset_1 posteriors.

To see whether changing the initial priors fixed this error, I used the alternative ones provided in the notebook:
```
gaussian.normalization = af.UniformPrior(lower_limit=0.0, upper_limit=1e2)
gaussian.sigma = af.UniformPrior(lower_limit=0.0, upper_limit=25.0)
```
Although the `PriorLimitException` is no longer present, I get still get the `ValueError: too many values to unpack (expected 3)`, as well as exceptions regarding NaN values for several datasets.

```
2022-03-13 13:32:48,179 - root - INFO - 20000 Iterations: Performing update (Visualization, outputting samples, etc.).
output/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation_3/dadacefaed2bd99700c4f7664421d5f9/dataset_0/optimization_0/image data.png
output/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation_3/dadacefaed2bd99700c4f7664421d5f9/dataset_0/optimization_0/image model_data.png
output/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation_3/dadacefaed2bd99700c4f7664421d5f9/dataset_0/optimization_0/image residual_map.png
output/howtofit/chapter_graphical_models/tutorial_3_expectation_propagation_3/dadacefaed2bd99700c4f7664421d5f9/dataset_0/optimization_0/image chi_squared_map.png
2022-03-13 13:32:52,708 - root - INFO - Removing zip file
2022-03-13 13:32:52,775 - autofit.graphical.mean_field - ERROR - nan parameter passed to UniformPrior
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/graphical/mean_field.py", line 401, in project_mean_field
    factor_dist = model_dist / self.cavity_dist
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/graphical/mean_field.py", line 194, in __truediv__
    {k: m / other.get(k, 1.0) for k, m in self.items()},
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/graphical/mean_field.py", line 194, in <dictcomp>
    {k: m / other.get(k, 1.0) for k, m in self.items()},
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/messages/transform_wrapper.py", line 104, in __truediv__
    self.instance() / other.instance()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/mapper/prior/prior.py", line 63, in _new_for_base_message
    params=message.parameters
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/autofit/mapper/prior/prior.py", line 79, in __init__
    "nan parameter passed to UniformPrior"
autofit.exc.MessageException: nan parameter passed to UniformPrior
```
Nonetheless, the optimisation seems to be progressing.

**Comment by Jammy2211** [comment]
The `PriorLimitException` is a known issue -- I meant to fix it but forgot.

If you are comfortable with editing the source code in site packages you can fix it by going to the following module:

`autofit.messages.abstract`

Going to line 267 and commenting out the line `assert_within_limits` in the method `factor`:

```
    def factor(self, x):
       # self.assert_within_limits(x)
        return self.logpdf(x)
```

**Comment by Jammy2211** [comment]
https://github.com/rhayes777/PyAutoFit/issues/489

**Comment by Jammy2211** [comment]
I am unclear on the parse issue, are you able to share the binder notebook?

**Comment by VictorForouhar** [comment]
Here's a copy of the notebook taken directly from the binder after I ran it: [tutorial_3_expectation_propagation.ipynb.tar.gz](https://github.com/rhayes777/PyAutoFit/files/8240286/tutorial_3_expectation_propagation.ipynb.tar.gz). I had to put it in a tar.gz as Github doesn't allow me to attach a .ipynb. Ignore the `PriorLimitException`, since I corrected it in my local site packages following your suggestion, and the parsing error still happens. 

The culprit of the parsing issue is in this [line](https://github.com/rhayes777/PyAutoFit/blob/9ae81e3dbff778ee4e3e40d730818c207309fd67/autofit/graphical/optimise.py#L162). It tries to unpack 3 values, but when I `print (status)` I only get a single string: `Optimisation succeeded`.

**Comment by Jammy2211** [comment]
I'm more just asking out of curiosity, but doesn't binder have a "share" button which you can use to send me straight to the binder notebook on your server?

I could be wrong!

**Comment by VictorForouhar** [comment]
I think you're right... does this link work?
https://mybinder.org/v2/gh/Jammy2211/autofit_workspace/f779cdbf9f23ea79b2ecbc970abd5d56fa401e89?urlpath=lab%2Ftree%2Fnotebooks%2Fhowtofit%2Fchapter_graphical_models%2Ftutorial_3_expectation_propagation.ipynb

**Comment by VictorForouhar** [comment]
Never mind, it seems like it takes you to the default notebook that has not been executed by me. Not sure how else to share aside from manually downloading my copy and attaching it in a comment
