### ISSUE TITLE
Decide what to do with bounds for Factor optimization

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#489]
Tutorial 3 of HowToFit breaks because of the So the line:
```
    def factor(self, x):
        self.assert_within_limits(x)
        return self.logpdf(x)
```

When the LaplaceFactorOptimiser tries to optimise a factor (e.g. an individual parameter), the minimize function still checks for prior limits. For example, one of the optimisations aims to update a parameter whose values is 7.85. It goes to 7.85 in the end, but the initial guesses also go to negative values that are outside its limits, causing the above function to raise an error and crash the code.

We either need to pass bounds based on the upper and lower limits of the parameter (which are contained in self.param_bounds) to 
the following scipy.minimize function:

```
    def _minimise(self, arrays_dict, **kwargs):
        x0 = self.transform * self.param_shapes.flatten(arrays_dict)
        opt_kws = {**self.default_kws, **kwargs}
        func = self.func_jacobian if opt_kws["jac"] else self

        print(self.param_bounds)
        
        return minimize(func, x0, **opt_kws)
```

Or disable prior checks for factor optimisations.

I guess which one we do depends on the specifics of transforms...

**Comment by rhayes777** [comment]
I think we discussed this before. Bounds should be passed to the optimiser I think

**Comment by rhayes777** [comment]
@matthewghgriffiths ?

**Comment by Jammy2211** [comment]
This code is from the now defunct old `LaplaceFactorOptimiser`, which should probably be deleted?

I dont think this issue occurs for the `LaplaceOptimiser` that Matthew implemented more recently.

**Comment by rhayes777** [comment]
Oh cool
