### ISSUE TITLE
Feature request - Lognormal distribution

### ISSUE THREAD

**Issue by VictorForouhar** [rhayes777/PyAutoFit#490]
I am interested in fitting hierarchical models to some simulated data. I expect one of the parameters governing the fit to follow a lognormal distribution. There is no implementation for this distribution in PyAutoFit as of yet. Although I can circumvent this using a Gaussian distribution and then using the drawn value, x, as an exponent for 10**x, I think it would be useful to have a lognormal distribution implemented in the code.

**Comment by matthewghgriffiths** [comment]
The LogNormal has been defined as a transformed NormalDistribution - see https://github.com/rhayes777/PyAutoFit/blob/3f8dc06e42c81b8fa67dbd29bd631fa2c36f69d4/autofit/messages/normal.py#L277

**Comment by Jammy2211** [comment]
Do we have the equivalent of a `LogNormalPrior` which uses this, or do we quickly need to implement this so that it can be used throughout autofit as a whole?

**Comment by VictorForouhar** [comment]
> Do we have the equivalent of a `LogNormalPrior` which uses this, or do we quickly need to implement this so that it can be used throughout autofit as a whole?

I can't find a `LogNormalPrior` in the code.

**Comment by Jammy2211** [comment]
Indeed, I believe Rich will sort this today. If not, I'll take a stab at it.

**Comment by rhayes777** [comment]
I've opened a PR for this. I've called it a 'LogGaussianPrior' to be consistent with our 'GaussianPrior'.

It seems to work OK but let me know if you have any issues. Using new Prior classes with the Graphical framework can cause issues as it's still fairly experimental.

```python
prior = af.LogGaussianPrior(
    mean=1.0,
    sigma=2.0,
)

**Comment by rhayes777** [comment]
OK it's merged into master
