### ISSUE TITLE
Out of bound parameters when using Gaussian priors during hierarchical model fitting

### ISSUE THREAD

**Issue by VictorForouhar** [rhayes777/PyAutoFit#495]
I am fitting a hierarchical model using parametric density profiles to several different profiles measured directly from simulations. The profile is fully specified using 5 parameters. My priors for three of said parameters are:
![image](https://user-images.githubusercontent.com/60343271/160134324-c80f0e21-6c0d-4fa6-b523-495661d1b324.png)

Once I start the fitting via factor_graph.optimise(), which uses EP, the procedure crashes and prints the following error:
![image](https://user-images.githubusercontent.com/60343271/160134816-7198d1c9-bfc4-441f-b800-b066e7545ef8.png)

@Jammy2211 and I investigated the cause, and it seems like the bounds on the Gaussian priors are not being enforced. For example, this is a set of parameters drawn by the optimiser: 
![image](https://user-images.githubusercontent.com/60343271/160135036-c27774e6-f3e8-4de4-b012-ca53b6bf581c.png)
![image](https://user-images.githubusercontent.com/60343271/160135130-0d25fcf8-469b-4e4f-be04-2d0fb5e3f2bd.png)

In same cases, it leads to complex densities being predicted:  
![image](https://user-images.githubusercontent.com/60343271/160135269-caeb4a22-dafb-4147-89ac-d67fc49c7f13.png)

Performing the fit using uniform priors instead of Gaussian works better, but the optimiser does not converge to an answer. Fitting each density profile individually (no EP, graphical or hierarchical modelling) works fine, regardless of whether Gaussian or Uniform priors are used.

**Comment by rhayes777** [comment]
Which optimiser are you using here?

**Comment by rhayes777** [comment]
@matthewghgriffiths I can't see how bounds are accounted for in the new implementation of LaplaceOptimiser?

**Comment by Jammy2211** [comment]
https://github.com/Jammy2211/autofit_workspace_test/blob/main/graphical/ep/gaussian_priors.py

Inspecting the `.identifer` file, the `lower_limit` on the `normarlization` parameter is being changed from `0.0` to `-inf`:

```
normalization
GaussianPrior
lower_limit
-inf
upper_limit
inf
mean
3.0
sigma
5.0
```

**Comment by VictorForouhar** [comment]
> Which optimiser are you using here?

It was the LaplaceOptimiser.

**Comment by VictorForouhar** [comment]
I can confirm that I don't get out of bound parameter errors anymore for the example I was testing.
