### ISSUE TITLE
Grid Searches

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#5]
**What is a grid search?**

A grid search is a non-linear search which searches over each dimension of parameter space by sampling values of the parameters between a lower and upper limit, in a uniform (or log-uniform, etc.) manner. For example, if we had a 3 dimension parameter space consisting of parameters p1, p2, p3, we may define a grid search where:

p1 = -0.1 -> 0.1 in bins of 0.01
p2 = 100 -> 200 in bins of 1.0
p3 = 5 -> 15 in bins of 5.0

In this case, p1 has 20 possible values, p2 100 and p3 3. This would mean our grid-search would require 20 x 100 x 3 = 6000 samples to complete.

The benefit of a grid-seaches are:

1) You can specify exactly in parameter space where you want to search for the highest likelihood model, which means known systematic solutions (e.g. the high-mass lens models in AutoLens) can be avoid. Or, they can be included, but the non-linear search itself will not 'get stuck' searching those regions of parameter space like something like MultiNest would.

2) The results are returned on a uniform grid of points, which can make interpreting the nature of the parameter space a lot simpler and can facilitate fitting smooth 'fitting functions' to the behaviour of certain parameters. This is exactly what we do when we perform a sensitivity analysis of substructures in a strong lens, and thus why a grid search is necessary.

The downside is:

1) It doesn't scale up to large dimensional problems, as the number of iterations quickly explodes. This is why we use MultiNest in general.

**How will we implement a grid search?**

A key difference between the simple example of a grid search above, and one implemented in AutoFit, is that in AutoFit a highest dimensional model may have been already fit in a previous phase. Therefore, we will want to perform a grid search on a sub-set of parameters, using a model consisting of many more parameters initialized already.

For example, in AutoLens, we may have initialized lens model with 20+ parameters, corresponding to the lens and source galaxies light and mass profiles. We may then want to perform a grid search on a sub-set of just three of these parameters, keeping the other 20+ parameters fixed to their most-likely values from the previous phase. The sensitivity analysis is the obvious example of this, where we fix all lens / source galaxy parameters and perform a 3D grid search over a substructures x, y and mass parameters.

In terms of implementation, this probably means we need a 'GridSearch' class in non_linear.py, and a new set of prior config files which are called for this grid search. This config files specify, by default, whether each parameter of a given model class:

1) Use the previous phase's most likely value as a Constant.
2) Are part of the grid-search, specifying their range of values and spacing. We can reuse classes like UniformPrior, as the grid search will span unit-hypercube values from 0.0 to 1.0.

The grid search itself is then fairly staighted forward, we just sample the specified models and output all of them (parameters, likelihoods, etc) to a file on the hard disk. This file can follow the same format as MultiNest files.

**MultiNest Grid Search**

We infact need a second type of grid-search. In this case, for each parameters that we grid-search over, we don't use just a constant value of that parameter at each point, but perform a complete MultiNest search of that parameter using uniform-priors spaced between its boundaries. For example, if we had two parameters:

p1 = 0.0 -> 1.0 in bins of 0.1
p2 = 10.0 -> 20.0 in bins of 5.0

This grid-search would perform 20 MultiNest searches, where the priors on each parameter are as follows:

MultiNest search 1:

p1 = UniformPrior(lower_limit=0.0, upper_limit=0.1)
p2 = UniformPrior(lower_limit=10.0, upper_limit=15.0)

MultiNest search 2:

p1 = UniformPrior(lower_limit=0.1, upper_limit=0.2)
p2 = UniformPrior(lower_limit=10.0, upper_limit=15.0)

MultiNest search 3:

p1 = UniformPrior(lower_limit=0.2, upper_limit=0.3)
p2 = UniformPrior(lower_limit=10.0, upper_limit=15.0)

... and so on up to MultiNest Search 10

MultiNest search 11:

p1 = UniformPrior(lower_limit=0.0, upper_limit=0.1)
p2 = UniformPrior(lower_limit=15.0, upper_limit=20.0)

... and repeat up to MultiNest search 20.

Obviously, this functionality should work the same way as above, whereby if we have an existing model with 20+ parameters, this MultiNest grid-search can use constants for the majority of parameters assuming the results of a previous phase.

This MultiNest grid-search is required for substructure detection, whereby when we add sub-halos we want them to have some freedom in changing their position / mass so as to best-fit the data.

**Comment by rhayes777** [comment]
Both grid search and non linear grid search are now implemented
