### ISSUE TITLE
Summed analysis with free parameter(s) does not output visualization

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#507]
The following summed analysis script does not create a free parameter across analyses:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/multi/no_free_parameter.py

It outputs visuals for each analysis in an `image/analysis` folder:

![image](https://user-images.githubusercontent.com/23455639/161313289-073a6a84-ceb8-418a-9cc4-5d6bc9992742.png)

When a free prameter is included, this folder is not created and visualization is not output:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/multi/x1_parameter.py

![image](https://user-images.githubusercontent.com/23455639/161313361-be78416f-4a86-4969-82b1-6fd1572e4bdb.png)

**Comment by Jammy2211** [comment]
This indeed fixed the issue, however the same issue now occurs for scripts wehich use the 

```
    analysis_list.append(
        al.AnalysisImaging(
            dataset=imaging
        ).with_model(
            model.replacing({
                model.galaxies.lens.bulge.intensity: lens_intensity,
                model.galaxies.source.bulge.intensity: source_intensity,
            })
        )
    )
```

API.

For example:

https://github.com/Jammy2211/autolens_workspace/blob/master/scripts/multi/modeling/wavelength_dependence.py

**Comment by rhayes777** [comment]
This looks like it works to me?

**Comment by rhayes777** [comment]
![Screenshot 2022-07-08 at 11 20 15](https://user-images.githubusercontent.com/6361906/177973853-a0585a09-737f-43bf-95ee-fc91c202a5ba.png)
