### ISSUE TITLE
Customize specific parameters of a model across analyses

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#515]
I create a model as follows:

```
lens = af.Model(
    al.Galaxy, redshift=0.5, bulge=al.lp.EllSersic, mass=al.mp.EllIsothermal, shear=al.mp.ExternalShear
)
source = af.Model(al.Galaxy, redshift=1.0, bulge=al.lp.EllSersic)

model = af.Collection(galaxies=af.Collection(lens=lens, source=source))
```

My two datasets are such different wavelengths that i want `lens.bugle.intensity` to be a free parameter in one dataset, but fixed to
zero in the other.

Is there a way to do this, or do we need to extend the following method like something as follows:

`analysis = analysis.with_free_parameters(model.galaxies.lens.bulge.intensity)`

to something like:

`analysis = analysis.with_fixed_parameters(model.galaxies.lens.bulge.intensity, [None, 0.0])`

Where None indiciates in the first analysis it remains free. 

I'm sure there is a better API for this.

**Comment by Jammy2211** [comment]
In fact, for the use case I have, removing a model component from one analysis class altogether is the correct approach:

`analysis = analysis.remove_component(model.galaxies.lens, [None, 0.0])`

**Comment by rhayes777** [comment]
Use the `replacing` method to create a model where any prior is set to None:

```python
model = model.replacing({
        model.centre: None
})
assert model.centre is None
```

Then a new analysis can easily be created:
```python
analysis = analysis.with_model(model)
```

You could also manually construct the model you need without using the `replacing` method.
