### ISSUE TITLE
Raise Exception is conf.instance.push does not point to config files

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#573]
If one incorrectly specifies a location without config files, e.g.:

```
config_path = path.join(workspace_path, "config_pix")
conf.instance.push(new_path=config_path)
```

If the `workspace_path` or whatever does not point to a valid set of `config` files, the code will still run (using the default configs in the source code repos).

If the path does not contain any valid config files this should raise an Exception.

**Comment by rhayes777** [comment]
I think this is implemented now
