### ISSUE TITLE
Add prior width option to use % of parameter value instead of float

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#6]
Currently, when we link the priors of a parameter together in two phases, we use the float value in the priors/width config file. For example:

[AbstractEllipticalSersic]
intensity=1.0
effective_radius=1.0
sersic_index = 1.2

The sersic index assumes a sigma=1.2 for the next phase's Gaussian prior (unless the errors on the parameter are greater than 1.2).

This works well for parameters like Sersic index, where we can generally anticipate the range of values from one phase to another will be covered by a value 1.2.

However, for a parameter like intensity, this isn't very useful. Sometimes, the intensity of a galaxy is of order 0.0001, sometimes its of order 1.0, sometimes maybe it is of order 100.0. There is no sensible single value we can use to generically link two intensities for very feasible galaxy value.

Therefore, we should introduce a 'percent' option in this config, which if used links the value as the % of the best-fit value inferred from the previous phase. For example:

[AbstractEllipticalSersic]
intensity=p, 50.0
effective_radius=v, 1.0
sersic_index = v, 1.2

Here, 'v' stands for 'value', and signifies the link uses the value as usual.

The 'p' stands for 'percent' and indiciates that the sigma used for the intensity is the best-fit value times 50%. For example, if intensity was 0.01, sigma=0.005, if it were 100.0, sigma=50.0.

**Comment by rhayes777** [comment]
Could I suggest that we use 'a' for absolute and 'r' for relative? It sits better with me than 'v' for value.

**Comment by rhayes777** [comment]
Also I think the relative expression should be a float. In this case 50% would be 0.5

**Comment by rhayes777** [comment]
This is now available as of 0.6.1. The 'a' marker will cause widths to behave as they did before. The 'r' marker will cause widths to be calculated by multiplying the associated value by the provided mean. For example, r, 0.5 with a mean of 2.0 would give a sigma of 1.0.

Relative widths should never be used to priors that could have a negative value.
