### ISSUE TITLE
Aggregator filter for path string

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#62]
The aggregator can filter for phase name, pipeline name, etc.

It'd be good too have a more general filter that looks at the phase's full path (e.g. /path/to/pipeline_name/phase_name/phase_tag/blah/blah) and filters for any matching strings in the path.

The reason for this is that advanced pipelines are getting some pretty hefty paths and its a bit complicated to filter for the actual tags of these paths. So, a simple filter that requires an input string to be in the path would go a long way.

**Comment by Jammy2211** [comment]
This still doesn't quite do what I need. Basically, I now have pipelines that change the analysis by 'tagging' the pipeline name. For example, I have a pipeline that depending on the setting:

- Aligns the bulge and disk centre of the lens light model -> The path structure for this analysis includes a tag pipeline_tag = "bulge_disk_align_centres".
- Doesn't align the centres -> Here he path structure include a tag pipeline_tag="bulge_disk".

The paths for the outputs are:

output/dataset_name/pipeline_name/pipeline_tag/phase_name/phase_tag/

In both cases, the pipeline_name and phase_names of the analysis are the same, thus filtering on pipelnie_name and phase_name is not sufficient to separate them.

We either need to include the pipeline tags in the metadata to filter for them (I think they are in the 'phase folders' attribute of each phase) or this filtering simply acts on the entire phase_path and skips the metadata (you can find and load a phase via the aggregator and then use its phase_path to filter it). 

Maybe the entire path should go in the metadata for this type of filtering?

**Comment by Jammy2211** [comment]
It works, but can we make the directory= take a string OR a list of strings, where the latter requires all entries in be in the path string?

**Comment by rhayes777** [comment]
You could just chain together filters:

aggregator.phases_with_contains(directory="one").phases_with_contains(directory="two")

**Comment by Jammy2211** [comment]
Fair enoguh.

Could we also get a filter_not_contain, so that it finds all aggregators that DONT have a certain string in.

**Comment by Jammy2211** [comment]
Gonna sugges we ge thte list input, to avoid note book cells like this:

```
agg_light = agg.filter(
    agg.directory.contains("pipeline_light")
)

agg_light = agg_light.filter(
    agg_light.directory.contains("general_fixed")
)

agg_light = agg_light.filter(
    agg_light.directory.contains("pix_voro_image")
)

agg_light = agg_light.filter(
    agg_light.directory.contains("disk_sersic")
)
```

**Comment by Jammy2211** [comment]
New API sorts this beautifully.
