### ISSUE TITLE
model.info placeholds when a pipeline is made

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#64]
At the moment, we have to wait for a phase to run for the model.info files to appear. This makes sense - afterall the priors depend don the results of earlier phases.

Would it be possible to output model.info placeholds before the pipeline is run? (e.g. when it is made). This would mean we could test the number of parameters in a model instantly, rather than having to wait for the pipeline to run. This would be useful as often when designing long pipelines its a pain to be sure that every phase behaves as you want.

The model.info could just use placeholders for the priors (e.g instead of GaussianPrior with values just put GaussianPrior with TBA's, or something). The iportant point is seeing instantly which components of the model are 'model' or 'instance's.

**Comment by Jammy2211** [comment]
If thesee placeholders (and the model.info in general) include the number of free parameters / instance parameters I can use them to unit test workspace pipelines... which will be a huge win.

**Comment by rhayes777** [comment]
I guess we just have the pipeline run through calling a model.info <http://model.info/> function on each phase at the point it runs

**Comment by Jammy2211** [comment]
Without NLO runs it wouldnt have the resutls necessary to determine the sigma's on the GaussianPriors of linked results though.

**Comment by rhayes777** [comment]
model.info is now saved as placeholder upon pipeline creation. This expresses promises by referring to their kind, path and phase name if there is one.
