### ISSUE TITLE
Inequalities in Prior linking

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#65]
we can current set two parameters equal to one anoother:

model.param1 = model.param2

It'd be good if we could define an inequality, so that is param2 is greater than param1 the model is instantly resampled:

model.param1 > model.param2.

**Comment by Jammy2211** [comment]
Couple of issues:

First, I can't seem to set up an assertion using a PriorModel, e.g.:

```
    gaussian_0 = af.PriorModel(al.lp.EllipticalGaussian)
    gaussian_1 = af.PriorModel(al.lp.EllipticalGaussian)

    gaussian_0.add_assertion(assertion=gaussian_0.sigma > gaussian_1.sigma)
```

The examples in the unit tests seem to set the model up as a ModelMapper - this isn't the API used in pipelines. Any thoguhts?

Secondly, the assetion are checked in the function instance_from_unit_vector. We want the assertion to work on physical values, e.g. we want the physical sigma value of gaussian 1 above to be lower than gaussian 0 irrespective of their priors. Are we safe to simply move the assertion functioon to physical_instance_from_unit_vector (or all appropriate functions) or does this require a little more thought?

**Comment by rhayes777** [comment]
Assertions are now checked when instance_for_arguments is called; it shouldn't matter which object they're attached to

**Comment by rhayes777** [comment]
Oh and yeah it works on arguments which is a dictionary mapping priors to physical values so it's physical values that are being compared.

**Comment by Jammy2211** [comment]
How do I pass an assertion to a pipeline?

The line 

`    gaussian_0.add_assertion(gaussian_0.sigma < gaussian_1.sigma)`

Passes a bool to the add_assetion method, not an AbstractAssertion.

**Comment by rhayes777** [comment]
It only works on Priors

**Comment by Jammy2211** [comment]
Do I use something instead of a PriorModel to make the thing with Priors?

Bare in mind I'm also doing things like:

```
    gaussian_0 = af.PriorModel(al.lp.EllipticalGaussian)
    gaussian_1 = af.PriorModel(al.lp.EllipticalGaussian)

    gaussian_1.centre = gaussian_0.centre
```

I can over ride the sigmas with priors if needs be!
