### ISSUE TITLE
Multi Analysis: Perform each non-linear search fit one by one

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#659]
The multi-analysis API allows one to combined summed `Analysis` objects from multiple datasets, and fit them simultaneously with a summed `log_likelihood_function`:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/multi/x1_parameter.py

I would like to have an option which uses the multi-fitting API, but instead of performing one non-linear search via a summed `log_likelihood_function` instead fits each dataset, one-by-one, using independent non-linear searches.

**Use case**

I have a problem with 32 datasets, where for each the model has 4 free parameters associated with them. If I fit them all simultaneously, I get 128 free parameters, but fitting each one one-by-one (in parameters of dimensionality 4) is fine in terms of the result.

**Model Structure**

By performing each fit one-by-one, even in the simplest of scenarios the model can change structure:

- If all analysis classes are fitted simultaneously, the parameters that are not free across each analysis class are only parameterized and fitted once. In the example script above, this means that the `centre`, `sigma` and `normalization` of the `Gaussian` are identical when fitted to 3 datasets.
- 
- By fitting each analysis independent, these parameters are refitting with new values each time, meaning the `centre`, `sigma` and `normalization` of the `Gaussian` are different for each fit.

**Outputs**

The goal of this feature is to make it so after fitting each analysis one-by-one, we can reuse the multi-analysis functionality. For example, the writing of results to hard-disk can use the same code in `CombinedAnalysis`. 

The returned `Result` list should also be equivalent in structure (if this is possible), so that the model-linking API of this result (see https://github.com/rhayes777/PyAutoFit/issues/660) can be used interchangeably with a run that does not perform individual fits.

**API**

I am imagine a simple API adjust so that instead of doing this:

```
analysis_list = []

for data, noise_map in zip(data_list, noise_map_list):
    analysis = af.ex.Analysis(data=data, noise_map=noise_map)
    analysis_list.append(analysis)

analysis = sum(analysis_list)

model = af.Model(af.ex.Gaussian)

analysis = analysis.with_free_parameters(model.sigma)

search = af.DynestyStatic(path_prefix="multi", name="x1_parameter")

result_list = search.fit(model=model, analysis=analysis)
```

One would do something like this:

```
analysis_list = []

for data, noise_map in zip(data_list, noise_map_list):
    analysis = af.ex.Analysis(data=data, noise_map=noise_map)
    analysis_list.append(analysis)

analysis = sum(analysis_list)

model = af.Model(af.ex.Gaussian)

analysis = analysis.with_free_parameters(model.sigma)

search = af.DynestyStatic(path_prefix="multi", name="x1_parameter")

result_list = search.fit(model=model, analysis=analysis.single_fit_mode)
```

Although I'm sure you can come up with a better API!

**Relational Models**

Multi analysis fitting can use relational models (e.g. `y = mx + c`). 

For these models, using the model-linking API after the fit is invalid, and an exception should be raised if relation models are combined with this feature.

**Comment by rhayes777** [comment]
What's wrong with:

```python
result_list = []
for analysis in analysis_list:
    result_list.append(search.fit(model=model, analysis=analysis))
