### ISSUE TITLE
Pickled datasets loaded from aggregator do not have pixel scale / 

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#66]
Datasets are pickled for use with the aggregator.

The datasets have a mask, e.g.:

```
datasets = aggregator.filter(phase=phase_name).dataset
print("Datasets:")
print(datasets, "\n")
print(datasets[0].image.mask)
```

However they appear to lose their pixel scale, which becomes "None":

`print(datasets[0].image.mask.pixel_scales)`

This makes using the aggregator a pain.

**Comment by rhayes777** [comment]
This was the same problem that caused the parallel grid search issue?

**Comment by Jammy2211** [comment]
Think so.
