### ISSUE TITLE
Aggregator with index filtering

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#70]
We can / will be able to make lists of outputs via the aggregator:

`outputs = aggregator.filter(phase=phase_name).output`

`tracers = aggregator.filter(phase=phase_name).tracer`

`fits = aggregator.filter(phase=phase_name).fit`

The problem is that for many images, this can get very memory heavy and crash machines. Filtering via phase / pipeline names is no use. So, it'd be good if there was an 'index range' which only did the calculation and returned the loaded outputs between a certain range of indexes, e.g.:

`outputs = aggregator.filter(phase=phase_name, indexes=[0, 5]).output`

**Comment by rhayes777** [comment]
You can now take a slice of an aggregator.

outputs = aggregator[:5].output
outputs = aggregator.filter(phase=phase_name)

etc.
