### ISSUE TITLE
Uniform prior should not set limits on parameter in later phases.

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#71]
Say  I have a parameter, param1, which has uniform prior 0.0 -> 10.0.

Then, in a later phase, this param has a GaussianPrior based on a previous result.

The change to new configs has meant that the GaussianPrior maintains the limits of 0.0 -> 10.0. But, we actually want it to be able to go beyond 10.0 for the GaussianPrior, if the model prefers.

It is the 'limit' config that should set the parameter range always, never the UniformPrior of a previous phase.

**Comment by Jammy2211** [comment]
This really warrants a regression test.

**Comment by rhayes777** [comment]
You can now add:

gaussian_limits: {
lower
upper
}

To a uniform prior configuration to indicate you want different limits for a gaussian
