### ISSUE TITLE
More informative error message when missing typing means model composition fails.

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#714]
The following class relies on typing to compose the model (e.g. loading priors via configs):

```
class Basis(LightProfile):
    def __init__(
        self,
        light_profile_list: List[LightProfile],
        regularization: Optional[aa.AbstractRegularization] = None,
    ):
```

If typing is removed, for example:

```
class Basis(LightProfile):
    def __init__(
        self,
        light_profile_list,
        regularization,
    ):
```

I get the following error message:

```
autoconf.exc.ConfigException: No prior config found for class:

Basis

For parameter name and path:

 regularization

 In any of the following directories:
```

Could we have it explicitly state that this could be because of typing msising from the __init__ method, as I often end up on a wild goose change for missing config files!

**Comment by rhayes777** [comment]
Is that not because the default value was removed as oppose to the typing?

**Comment by Jammy2211** [comment]
The default value has never been in this class so I guess its cause typing was removed?

**Comment by Jammy2211** [comment]
Oh right for the `regularization`... Im not sure.

I have another use case where only the removal of typing (but retaining a default input value of `None`) produces the same error, so think its a typing thing.

**Comment by rhayes777** [comment]
OK will investigate
