### ISSUE TITLE
If phase is skipped because its done, still update metadata

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#73]
We often have to rerun analyses to update metadata to a new version of autofit.

If the phase skipping feature skips the updating of metadata, we cant do this.

So, we need to double check it isnt omitted.

**Comment by rhayes777** [comment]
metadata is written at the pipeline level whilst phase skipping occurs in mutlinest. As far as I can tell metadata is rewritten even if a phase is skipped
