### ISSUE TITLE
Adding MPI Support

### ISSUE THREAD

**Issue by jacob-hjortlund** [rhayes777/PyAutoFit#743]
Currently PyAutoFit only supports parallelization via `multiprocessing`. Some of the non-linear search methods (`emcee`, `ultranest`) also support parallelization via MPI. Adding MPI as an alternative option for parallelization would let people scale their models across many nodes on their HPCs.

Parallelization is currently supported using the `SneakyPool` class, which is a plug-in replacement for the `multiprocessing` pool. As far as I understand it `SneakyPool` avoids overhead related to data transfer by associating the fitness function with each process when creating the pool, which is equivalent to declaring the fitness function as a global variable.

We should be able to add MPI support in a similar manner by using `mpi4py.futures.MPIPoolExecutor`. This uses a pool of MPI processes to execute calls asynchronously, and should be usable as a drop-in replacement for `multiprocessing.Pool` when using MPI. Data transfer overhead can be avoided by passing the fitness function as a global variable to the pool using the `global` kwarg when initializing the pool, similar to `SneakyPool`.

The choice of whether to use `SneakyPool` or  `MPIPoolExecutor` could be done under the hood by checking the size of the MPI communicator via `mpi4py.MPI.COMM_WORLD.Get_size`. If MPI is not being used this should be 1, and if the code was run using mpiexec then it should be larger than one, in which case the MPI pool would be used.

**Comment by Jammy2211** [comment]
Sounds great, me and Rich were discussing this this morning.

Question -- I assume that for this to work we require that the search (emcee, UltraNest) have internal support for MPI?

We'll get it implemented either way, just curious.

**Comment by jacob-hjortlund** [comment]
Any non-linear search that can be parallelized by passing a user defined pool with a map method should be able to be parallelized via MPI, so both emcee, UltraNest and Dynesty can be run in parallel using `MPIPoolExecutor`. [See here](https://dynesty.readthedocs.io/en/latest/faq.html#pool-parallelization-questions) (see 3rd to last section) for elaboration on Dynesty where they use a `schwimmbad.MPIPool`, similar to how emcee is parallelized with MPI.

So I'd think we don't need to explictly check for internal MPI support, but rather if the method is parallelizable at all.

**Comment by Jammy2211** [comment]
MPI dynesty would be absolutely insane 😱.
