### ISSUE TITLE
Refactoring SneakyPool Using Singletons

### ISSUE THREAD

**Issue by jacob-hjortlund** [rhayes777/PyAutoFit#747]
Currently `SneakyPool` is used to ensure that data isn't passed to processes during every evaluation. As far as I understand, the way this is implemented under the hood is the following:

- Pool is initialized, creating N `SneakyProcess` instances
- Each of these processes are wrappers around `multiprocessing.Process`, with the main difference being that they have a jobargs attribute containing the passed fitness object
- When calling map each process checks if the function being passed to map is contained within the jobargs. If this is the case, the jobarg is used instead, avoiding the need to send the function to the process

This could be refactored by copying the approach used by Dynesty ([see here](https://github.com/joshspeagle/dynesty/blob/master/py/dynesty/pool.py)). This approach makes use of a custom `Pool` object that acts as a context manager around a `multiprocessing.Pool` object. The way it avoids passing data for each call is the following:

- Instantiate pool, passing a loglikelihood function (fitness object in our case)
- Cache the fitness function in a FunctionCache singleton
- Add the cached fitness function as an attribute of the pool (`Pool.loglike`)
- Pass `Pool.loglike` to the Dynesty sampler

This is basically a classy version of setting the loglikelihood function as a global variable. The benefit is that it is imo a good bit more readable than `SneakyPool` (soz @rhayes777 <3). I think it might be worth it to refactor `SneakyPool` to follow this approach.

This would also make #743 easier to implement. No conflict of interest, promise.

**Comment by rhayes777** [comment]
This sounds great. I wonder whether the singleton is necessary; if it is it's not the end of the world.

As Dynesty already has its own implementation we don't need this solution to support Dynesty. From looking at the code it seems that we only use SneakyPool with EMCEE.

**Comment by jacob-hjortlund** [comment]
We would need this solution to support Dynesty if we want to add MPI support. We'd need to pass an MPI aware pool instead of the Dynesty pool. I was thinking to make the refactored SneakyPool pick between multiprocessing and MPI under the hood by checking the MPI world size (think number of processes chosen when using mpiexec). SneakyPool would then create an MPI pool when world size > 1 and n_cores > 1 and a multiprocessing pool when world size == 1 and n_cores > 1.

**Comment by rhayes777** [comment]
Sure we could definitely pass a custom pool to Dynesty again. We could also reuse this wherever an optimiser supports passing of a custom pool object
