### ISSUE TITLE
Output mask pickle for phase

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#77]
If a phase is passed a mask in its run function, can we have it output as a pickle for aggregator loading analgoous to a dataset?

e.g. masks = aggregator.mask

At this point, it may be worth having a 'aggregator' folder or something in a phase for all the different pickles we are creating...

**Comment by rhayes777** [comment]
Aggregator output is now generalised. 

If there is any .pickle in the directory then calling the name of that object on the output returns the deserialised instance.

For example phase_output.mask returns the contents of mask.pickle, phase_output.random returns the contents of random.pickle
