### ISSUE TITLE
Fast access to results of a pipeline

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#8]
After we run a pipeline, we return the results of the pipeline, e.g.

```
pipeline = lens_light_and_source_inversion.make_pipeline(pipeline_path='/slacs/' + lens_name)
result = pipeline.run(data=ccd_data)
```

Normally, we don't want too do anything with the results, as the pipeline visualizes and outputs everything we need. However, if we want to customize the visualize of the results, the results object is handy, as it gives us access to everything we need, e.g.
```

from autolens.model.inversion.plotters import inversion_plotters
inversion_plotters.plot_reconstructed_pixelization(inversion=result[4].most_likely_fit.inversion)
```

This allows us to customize the figures output via the plotters, e.g. in a Juypter notebook.

```
from autolens.model.inversion.plotters import inversion_plotters

inversion_plotters.plot_reconstructed_pixelization(inversion=result[4].most_likely_fit.inversion, 
                                                   title='SLACS1430+4105 Reconstructed Source', 
                                                   xlabelsize=24, ylabelsize=24, xyticksize=24)
```

However, accessing these results is slow. We have to run the entire pipeline, which involves multinest running an optimizer and lots of visualization. It would be good if when we ran the pipeline, we could tell it to go through the entire pipeline so as to generate the results, but skip running opttimiers / visualization so that it is a lot faster.

**Comment by rhayes777** [comment]
I'm confused as to how it would generate results without running optimisers

**Comment by rhayes777** [comment]
Bump

**Comment by Jammy2211** [comment]
Aggregator has pretty much negated the need to do this, so closing.
