### ISSUE TITLE
Optional to only return completed results from aggregator

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#81]
Atm, the aggregator returns all results irrespective of if the runs are completed or not (e.g. if MultiNest is 50% of the way through, so the files exist, the aggregator loads these results).

Could we have a flag that if True only returns completed results (using the completed file that skips runs if they have finished).

**Comment by rhayes777** [comment]
```python
Aggregator(directory, completed_only=True)
```
Returns only phases for which a .completed file exists.

All phases now created a .completed file when they finish running.
