### ISSUE TITLE
Automated test of search outputs and resume

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#815]
Previously, we test every search via the `test_autofit/output` folder:

![image](https://github.com/rhayes777/PyAutoFit/assets/23455639/fc73b8fe-7e24-4427-bc94-4c65afb9f8e7)

This has become very difficult to maintain, due to the increase in searches and size of the code base. It included a need to constantly update the output search results based on autofit formats.

Could we instead have a generic unit test that runs a search (very fast via a limited number of iterations), runs it again (resuming the completed results from hard-disk) and asserts something generic about the result being computed? I think this will catch most use cases.

I have deleted these tests for now.

**Comment by rhayes777** [comment]
What do we want the test to prove?

**Comment by Jammy2211** [comment]
Currently, unit tests do not test that the `fit` method of every search runs successfully (and does not raise an error).

This has proven difficult to test, as previous we had loads of manual files to speed up the process.

It seems like an important thing to have at the unit test level, and something that can be easily automated.

We could just leave it to integration build server tests though.

**Comment by Jammy2211** [comment]
The test would include a mechanism to ensure features like resuming from an existing fit (e.g. made via a termination) work.
