### ISSUE TITLE
GirdSearchResult Redesign

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#855]
A non-linear search of searches outputs a `GridSearchResult` as a .pickle file here:

```
        def save_results():
            self.paths.save_object(
                "result",
                builder()
            )
```

The results are output to a dedicated `files` folder in the grid search:

![image](https://github.com/rhayes777/PyAutoFit/assets/23455639/ff6641d6-6c10-401b-ac2b-d19fb868d1c9)

We should update this so that all quantities are output to human readable formats (e.g. .json).

**Reducing File Size**

An issue with the `GridSearchResult` is that it includes the list of `Result` objects for every cell in a grid search. This includes attributes which take up a lot of disk space (e.g. the `Samples` object).

For picking / output they take up too much disk space (and are accessible via the aggregator anyway).

However, certain `GridSearchResult` properties use attributes in the `results`. However, it only uses information contained in the `SamplesSummary` object. 

Therefore, can we also refactor the `GridSearchResult` to not take as input `results` but instead a `samples_summary_list`.

**Integration Test**

The following script has assertions which include attributes which use the `Samples`, so should help fixing the code:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/scripts/database/scrape/grid_search.py

**Comment by rhayes777** [comment]
It looks like the `save_object` method is still used in a bunch of notebooks. It might be an idea to remove it to force saving as JSON

**Comment by rhayes777** [comment]
The script gives this error. I've tried removing output.

```python-stacktrace
autofit.exc.SearchException: 
                A Dynesty sampler has been loaded and its pool type is not the same as the input pool type.

                This means that the original samples in dynesty were computed with or without a 
                multiprocessing pool, whereas the run is now trying to use a multiprocessing pool.

                This could indiciate the number of cores have change values or Python multiprocessing
                has been disabled and then enabled.

**Comment by Jammy2211** [comment]
> It looks like the save_object method is still used in a bunch of notebooks. It might be an idea to remove it to force saving as JSON

What notebooks? As far as I can tell `save_object` is not being used anywhere it should not be.

**Comment by Jammy2211** [comment]
> The script gives this error. I've tried removing output.

It runs fine for me, as far as I can tell this has to be due to you having existing results its trying to load:

```
        if checkpoint_exists:
            search_internal = StaticSampler.restore(fname=self.checkpoint_file, pool=pool)

            uses_pool = self.read_uses_pool()

            self.check_pool(uses_pool=uses_pool, pool=pool) # Exception raised here.

            return search_internal
```
