### ISSUE TITLE
Grid Search Result LimitList of parameter

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#861]
A `GridSearchResult` has a `LimitList` type which provides list of lists of quantities that are mapped over, for example the upper limit of the prior of every grid search parameter:

```
    @property
    def upper_limits_lists(self) -> LimitLists:
        """
        The upper values for each grid square
        """
        return [
            [limit + self.step_size for limit in limits]
            for limits in self.lower_limits_lists
        ]
```

This `LimitList` structure is a key property of the `GridSearchResult`, it is represents the structure of all results performed for the `GridSearch`.

In `PyAutoLens`, I manually map over inferred results to plot the results of a grid search:

```
        instance_list = [
            None if samples.median_pdf() is None else samples.median_pdf()
            for samples in self.grid_search_result_with_subhalo.samples
        ]

        return [
                None if instance is None else instance.galaxies.subhalo.mass.mass_at_200
                for instance in instance_list
            ]
```

A much more concise API should be available, where I simply query the name of a parameter and quantity I want, and the `LimitList` corresponding to it is returned.

```
mass_at_200_list = self.grid_search_result.values(parameter="mass_at_200", quantity=samples.median_pdf())
```

I am not 100% sure on the exact API, but you should get the idea that for a `GridSearchResult` I should be able to get the `LimitList` for any parameter in `GridSearchResult.samples` and should be able to choose what attribute of the `Samples` I want (e.g. `median_pdf`, `max_log_likelihood`).

**Comment by Jammy2211** [comment]
Whilst things work for simple autofit cases, I am not getting success with an autolens fit.

This is shown in the following script:

https://github.com/Jammy2211/autolens_workspace_test/blob/main/scripts/database/scrape/slam_subhalo.py

I have put the following code in:

```
"""
THIS IS FOR RICH:
"""
grid_search_result = subhalo_results[1]

print(grid_search_result.attribute_grid("mass_at_200"))
ddd
```

Which produces the error:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autolens_workspace_test/scripts/database/scrape/slam_subhalo.py", line 209, in <module>
    print(grid_search_result.attribute_grid("mass_at_200"))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/grid/grid_search/result.py", line 208, in attribute_grid
    attribute = getattr(attribute, attribute_name)
AttributeError: 'ModelInstance' object has no attribute 'mass_at_200'
```

**Comment by rhayes777** [comment]
Is mass_at_200 an attribute of the model? You might need a more specific path like 'galaxies.lens.mass_profile.mass_at_200'

**Comment by Jammy2211** [comment]
Ok it works if I specify the full path `"galaxies.subhalo.mass.mass_at_200"`.

But not for `mass_at_200`.

Based on the PR I thought full path specificiation wasnt necessary?

**Comment by rhayes777** [comment]
Nope full path is required otherwise there could be ambiguity

**Comment by Jammy2211** [comment]
Great thanks!
