### ISSUE TITLE
Interchangeable list / ndarray for GridSearchResults

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#865]
Currently, a `GridSearchResult` stores many quantities in two formats, as a list (which is tied to the composition of the grid) and as a converted ndarrray format often given the suffix `native`:

```
    @property
    def log_evidences_native(self):
        """
        The log evidence of every grid search on a NumPy array whose shape is the native dimensions of the grid search.

        For example, for a 2x2 grid search the shape of the Numpy array is (2,2) and it is numerically ordered such
        that the first search's log evidence (corresponding to unit priors (0.0, 0.0)) are in the first value (E.g.
        entry [0, 0]) of the NumPy array.
        """
        return self._list_to_native(
            lst=[samples.log_evidence for samples in self.samples]
        )
```

The `native` arrays are created via this method:

```
    def _list_to_native(self, lst: List):
        return np.reshape(np.array(lst), self.shape)
```

This is leading to a lot of code repetition (e.g. converting from one to another) and makes things quite confusing.

I considered trying to just inherit and extend a Python list with a method which includes the `native` format, which any quantities in the `GridSearchResult` could then use, but it didnt work:

```
class ValueList(list):

    def __init__(self, values):

        super().__init__(values)

    @property
    def native(self):
        return np.reshape(np.array(self), self.shape)
```

Do you have a suggestion for how best I can refactor the code to remove the specific `native` methods and have a structure which can easily alternative between the lists and ndarray format, e.g.

`print(log_evidence)`
`print(log_evidence.native)`.

Happy to implement it myself just want to make sure I start on the right path.

**Comment by rhayes777** [comment]
Yeah I guess that looks reasonable. I suppose you would have to pass the shape to the value list
