### ISSUE TITLE
Place holder priors on model.info

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#873]
I can create a model without a config file for its priors:

```
class Coefficient:

    def __init__(self, value : float = 1.0):

        self.value = value

model = af.Model(Coefficient)
```

However if I print its `model.info` I get nothing:

```
print(model.info)
```

```

Total Free Parameters = 0

```

The model is composed correctly though, and if I manually add a `UniformPrior` I get the expected `info`:

```
model = af.Model(Coefficient)

model.value = af.UniformPrior(lower_limit=0.0, upper_limit=1.0)

print(model.info)
```

```
Total Free Parameters = 1

model                                                                           Coefficient (N=1)

value                                                                           UniformPrior [0], lower_limit = 0.0, upper_limit = 1.0
```

This is to do with how we added a placeholder for models with unknown `UniformPriors`.

Could we have some sort of a `PriorPlaceholder` appear in the `model.info` so a user knows they have to speciffy it, something like:

```
Total Free Parameters = 1

model                                                                           Coefficient (N=1)

value                                                                             PlaceholderPrior
```

**Comment by rhayes777** [comment]
Should an exception be raised if they instantiate a model without a value set?

I have a feeling we changed the behaviour to be this way intentionally?

**Comment by Jammy2211** [comment]
An Exception is raised when the `model` is passed to `search.fit`.

We changed the behaviour to make it this way, so that a user could still manually set the priors in the Python script and then run the fit without issue.

I think where the exception is raised is fine, we just need a place holder so the `info` is displayed clearly.

**Comment by rhayes777** [comment]
Yeah I see looking at it now
