### ISSUE TITLE
Make sym links play nicely when mirroring data between a laptop and supercomputer

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#9]
We are now going to begin running large analyses on the Durham super computing, for both AutoLens and AutoCTI. This effectively means we want to 'mirror' the output directory of each on our laptops and the super computer, so we can run large jobs on the super computer but analyse the output on our laptops. Furthermore, we may want to 'initialize' a model (e.g. phase 1) on our laptop to make sure it works and then send those results to the super computer for a more intensive analysis of the subsequent phases.

Passing data is straight forward, we can just make sure everyone has the appropriate rsync command line commands to pass data between the two.

However, I'm gonna guess that this is going to completely ruin our sym links to the MultiNest optimizer folder? YAY!

I'm not totally sure how we deal with this. I guess we could make it so that, by default, AutoLens always sets up a new optiimzer folder and sym link on every single run, and copies the files in the optimizer_backup folder to this? Its ugly, but erm...yeah.

I havent explicitly check that rsync plays nicely with sym links from laptops to super computers either.

**Comment by rhayes777** [comment]
The files in the sym linked folder are copied to the backup folder intermittently and at the end of an optimisation. When an optimiser class is instantiated it attempts to copy files from the backup folder (if it exists) to the sym linked folder. This should mean that a project copied between computers will behave in the required way.
