### ISSUE TITLE
Prevent clutter due to pyvis

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#929]
After installing `pyvis` there is annoying clutter and folder appearing where I run modeling scripts:

![image](https://github.com/rhayes777/PyAutoFit/assets/23455639/d02af4a7-cf04-4b23-8be4-9c6f37f17c42)

**Comment by Jammy2211** [comment]
There is still a `model_graph.html` file which should be disabled:

![image](https://github.com/rhayes777/PyAutoFit/assets/23455639/fa70fc69-ff50-4133-a65c-14c85b640ca2)

**Comment by rhayes777** [comment]
Yeah probably but it's nice being able to pan, zoom and manipulate the graph

**Comment by rhayes777** [comment]
Looks like the library I used only supports export to HTML
