### ISSUE TITLE
`LogGaussianPrior` raises Exception

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#932]
The following script uses ` LogGaussianPrior` and produces an exception:

https://github.com/Jammy2211/autofit_workspace_test/blob/main/scripts/searches/DynestyStatic.py

The exception:

```
2024-02-12 09:53:38,721 - DynestyStatic - INFO - The output path of this fit is /mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test/output/searches/DynestyStatic/431e743943ea071dcffa55a0db2535b6
2024-02-12 09:53:38,721 - DynestyStatic - INFO - Outputting pre-fit files (e.g. model.info, visualization).
2024-02-12 09:53:38,948 - DynestyStatic - INFO - Starting new Dynesty non-linear search (no previous samples found).
2024-02-12 09:53:38,993 - autofit.non_linear.initializer - INFO - Generating initial samples of model, which are subject to prior limits and other constraints.
/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/messages/transform.py:195: RuntimeWarning: divide by zero encountered in log
  return self.func(x, *self.args)
1122it [00:04, 241.60it/s, +50 | bound: 40 | nc: 1 | ncall: 4861 | eff(%): 24.361 | loglstar:   -inf < -43.295 <    inf | logz: -62.652 +/-  0.593 | dlogz:  0.001 >  0.059]
2024-02-12 09:53:43,694 - DynestyStatic - INFO - Fit Still Running: Updating results after 10000 iterations (see output folder for latest visualization, samples, etc.)
Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 1053, in samples_from
    return self.samples_via_internal_from(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/nest/dynesty/search/abstract.py", line 237, in samples_via_internal_from
    log_prior_list = model.log_prior_list_from(parameter_lists=parameter_lists)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1578, in log_prior_list_from
    return [
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1579, in <listcomp>
    sum(self.log_prior_list_from_vector(vector=vector))
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1077, in log_prior_list_from_vector
    return list(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior_model/abstract.py", line 1079, in <lambda>
    lambda prior_tuple, value: prior_tuple.prior.log_prior_from_value(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/mapper/prior/abstract.py", line 188, in __getattr__
    return getattr(self.message, item)
AttributeError: 'TransformedMessage' object has no attribute 'log_prior_from_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test/scripts/searches/DynestyStatic.py", line 89, in <module>
    result = search.fit(model=model, analysis=analysis)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 565, in fit
    result = self.start_resume_fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 683, in start_resume_fit
    search_internal = self._fit(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/nest/dynesty/search/abstract.py", line 196, in _fit
    self.perform_update(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 914, in perform_update
    samples = self.samples_from(model=model, search_internal=search_internal)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 1057, in samples_from
    return self.samples_via_csv_from(model=model)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/search/abstract_search.py", line 1080, in samples_via_csv_from
    return self.samples_cls.from_csv(
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/samples.py", line 203, in from_csv
    sample_list = paths.load_samples()
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/paths/directory.py", line 216, in load_samples
    return load_from_table(filename=self._samples_file)
  File "/mnt/c/Users/Jammy/Code/PyAuto/PyAutoFit/autofit/non_linear/samples/sample.py", line 292, in load_from_table
    with open(filename, "r+", newline="") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Jammy/Code/PyAuto/autofit_workspace_test/output/searches/DynestyStatic/431e743943ea071dcffa55a0db2535b6/files/samples.csv'
```

**Comment by rhayes777** [comment]
@matthewghgriffiths I've added an implementation for this method in the LogGaussianPrior class but I think more generally we should probably implement the method on the TransformedMessage

**Comment by rhayes777** [comment]
No problem!

**Comment by jhod0** [comment]
@matthewghgriffiths does that mean that this implementation is correct, or does it need to be confirmed that this `log_value_from_prior` gives the same as `logpdf`? The current `logpdf` is defined in a superclass so it was not clear to me how it works in this `LogGaussianPrior` class.

**Comment by jhod0** [comment]
Also, I'm not sure that the current documentation is correct. The documentation says that the `mean` and `sigma` are interpreted as log base 10, but it looks like they are interpreted as *natural* log.

This is a plot of `np.exp(prior.logpdf(x))` for a different set of `mean`s and `sigma`s which shows the PDFs means are interpreted as natural log.


![image](https://github.com/rhayes777/PyAutoFit/assets/8944001/66a3cc26-a89e-4b31-9db4-70cd07cf4f19)

**Comment by jhod0** [comment]
It also looks to me that the current `logpdf` does not give the right behavior.

If `y = exp(x)`, and `x` is distributed as a Gaussian `N(\mu, \sigma)`, then `P(y) = P(x)/y`. It looks like `logpdf` is missing the `/y` part and just forwarding the `N(\mu, \sigma)` logpdf.

This plot compares the `logpdf` of `LogGaussianPrior` and `GaussianPrior` for the values mean=ln(10), sigma=ln(2). The orange and green curves are identical, and the blue curve (which I think is the correct `logPDF` of `LogGaussianPrior`) is offset below them.

I hope I'm not just getting the math wrong here - I just want to be sure this prior works correctly before I use it.

![image](https://github.com/rhayes777/PyAutoFit/assets/8944001/b782218a-f219-4925-8f07-891532df4384)

**Comment by rhayes777** [comment]
Apologies I'll take a look again Monday

**Comment by matthewghgriffiths** [comment]
Ah good catch, it looks like the Jacobian determinant of the change of variables is no longer being calculated in the change of variables transform - https://github.com/rhayes777/PyAutoFit/blob/10f5f9beda014d7cc7586d4bb1623529ff3be959/autofit/messages/composed_transform.py#L221-L223

I think the code should be something like, 

```
    def calc_log_base_measure(self, x) -> np.ndarray:
        z, logd = self._transform(x), self.transform_det(x) # we should be able to use transform.transform_det to calculate this
        return self.base_message.calc_log_base_measure(x) + logd
```

**Comment by matthewghgriffiths** [comment]
This also means that the logpdf_gradient code won't work

**Comment by matthewghgriffiths** [comment]
Potentially the `_factor` method calculates the logpdf correctly -- https://github.com/rhayes777/PyAutoFit/blob/10f5f9beda014d7cc7586d4bb1623529ff3be959/autofit/messages/composed_transform.py#L250

**Comment by rhayes777** [comment]
Any chance you've got a minute to implement this Matt? You'll do a better
job of it than I would.

**Comment by matthewghgriffiths** [comment]
Had a go here - https://github.com/rhayes777/PyAutoFit/tree/feature/loguniform

Updated some tests and stuff (including fixing the implementation of `Log10UniformNormal`), but there's one test that failed:

To get the correct (log) density for the transformed messages you need to call the TransformedMessage.factor or TransformedMessage.exp_factor. Due to the arithmetic of the message passing we only need to account for the change of variables once in the approximation, so in the EP autofit we account for this change of variables when modelling the prior itself as a factor (which is why it's only calculated then). 

```
===================================================================== short test summary info =====================================================================
FAILED test_autofit/graphical/gaussian/test_prior_factor.py::test_log_likelihood_function - assert -1.1102230246251565e-16 == -0.9189385332046727 ± 9.2e-09
===================================================== 1 failed, 1077 passed, 164 warnings in 78.16s (0:01:18) =====================================================
```

But I'm not quite sure what's going on here and why it's failing. 


@jhod0 The following code 

```
import numpy as np 
from scipy import integrate

import matplotlib.pyplot as plt

import autofit
from autofit import messages

message = messages.LogNormalMessage(1, 2)

x = np.logspace(-5, 5, 1000)

p_x = message.pdf(x)
int_p, err_p =  integrate.quad(message.pdf, 0, np.inf)
plt.semilogx(x, p_x, label=rf'$\int_0^\infty logpdf(x)\,dx = $ {int_p:.2f}')

f_x = np.exp(message.factor(x))

int_f, err_f =  integrate.quad(message.exp_factor, 0, np.inf)
plt.semilogx(x, f_x, label=rf'$\int_0^\infty exp(factor(x))\,dx = $ {int_f:.2f}')

plt.legend()

assert np.isclose(int_f, 1, atol=err_f)

message = messages.Log10NormalMessage(2, 1)

x = np.logspace(-10, 10, 1000)

p_x = message.pdf(x)
int_p, err_p =  integrate.quad(message.pdf, 0, np.inf)
plt.semilogx(x, p_x, label=rf'$\int_0^\infty logpdf(x)\,dx = $ {int_p:.2f}')

f_x = np.exp(message.factor(x))

int_f, err_f =  integrate.quad(message.exp_factor(x), 0, np.inf)
plt.semilogx(x, f_x, label=rf'$\int_0^\infty exp(factor(x))\,dx = $ {int_f:.2f}')

plt.legend()
assert np.isclose(int_f, 1, atol=err_f)
```

Should generate the following plots, 
![image](https://github.com/rhayes777/PyAutoFit/assets/7985320/cea8b0d8-521f-44fd-8324-705fdf75fdfb)
![image](https://github.com/rhayes777/PyAutoFit/assets/7985320/70154a6d-61d6-4df1-a4c9-ff5005df2ea3)

**Comment by rhayes777** [comment]
That test looked fairly arbitrary so I've removed it as everything else passes.

**Comment by jhod0** [comment]
I don't believe this has actually fixed the problems - the documentation of `LogGaussian` still says base 10 when it is base e, the normalization of the `logpdf` appears to be wrong, and the `logpdf` and `log_prior_from_value` methods still give different values.

I am using commit b13a8c03666381c981de24cd75e376dc8d6051a4 to make these plots, which includes the changes from #943.

This plot is a comparison of the `logpdf` and `log_prior_from_value` methods. It looks like they both have the right shape but `log_prior_from_value` has a sign error. Since I gave it's mean as ln(2) and the pdf peaks around 20, it looks like it's base e and not 10

![image](https://github.com/rhayes777/PyAutoFit/assets/8944001/db0cc88a-b4ef-449f-b601-26d911d170ce)


Here's integrating P(x)dx for three different values of the priors, and they give >1

```python
In [50]: from scipy import integrate

In [51]: integrate.quad(lambda x: np.exp(prior.logpdf(x)), 0, 400)
Out[51]: (20.40402680053504, 1.4569143418964071e-07)

In [52]: prior = LogGaussianPrior(np.log(50), 1)

In [53]: integrate.quad(lambda x: np.exp(prior.logpdf(x)), 0, 400)
Out[53]: (70.87890083913956, 5.456650821413536e-08)

In [54]: prior = LogGaussianPrior(np.log(10), 0.5)

In [55]: integrate.quad(lambda x: np.exp(prior.logpdf(x)), 0, 400)
Out[55]: (11.331484530633613, 2.5962434648491115e-08)
```

**Comment by jhod0** [comment]
Ignoring all of your abstract machinery with `Transform`s etc, I made a simple working log normal prior class [here](https://github.com/jhod0/PyAutoFit/blob/f21c73b1e88961b53e219fbdbf9cbca65d38ccfa/autofit/mapper/prior/log_normal.py).

It just has two methods, one to draw samples, and one to compute `logpdf`.

This plot draws 100k samples, and shows that the histogram is consistent with the PDF implementation for 3 different settings

![example_01_check](https://github.com/rhayes777/PyAutoFit/assets/8944001/7be76bfc-72fb-4245-8b50-106c69cbd274)

This plot is just showing that it uses `upper_limit` and `lower_limit` correctly, adjusting the normalization right

![example_02_limits](https://github.com/rhayes777/PyAutoFit/assets/8944001/34598f29-2ae4-4a69-8bb1-77166a4263e8)

**Comment by matthewghgriffiths** [comment]
@jhod0  did you use `LogNormal.logpdf` or `LogNormal.factor` to calculate the probability density? The 'LogNormal.logpdf' will not match the histograms (it returns the log density of the underlying Normal distribution) - you'll need to use the `LogNormal.factor` to get the correct log density.

**Comment by jhod0** [comment]
@matthewghgriffiths Thanks, it looks like `factor` gives the right behavior!

(But could I suggest changing that, it seems excessively confusing to a user that `logpdf` does NOT in fact give `log P(x)`. It was not obvious to me that `logpdf` is not what you want, and you actually need to use something called `factor` instead.)

Here is a plot like the ones I made with my own code, showing that the draws are consistent with the overall density normalization. Great! The documentation still incorrectly says it is base 10, but I can make a quick PR fixing that?

![image](https://github.com/rhayes777/PyAutoFit/assets/8944001/af4610e2-663d-4465-bd15-2be4e204d687)

**Comment by rhayes777** [comment]
Sure please do

**Comment by matthewghgriffiths** [comment]
You are right that it's confusing (it confused me as well!) Unfortunately
all the mean field message passing routines (which is where logpdf methods
are primarily called) need to work with the untransformed probability
density for the mathematics to work out. It's when treating the
distribution as a _factor_ or a _prior_ that we need to use the proper
transformed density.
