### ISSUE TITLE
Pickling a GridSearchResult

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#98]
I have made it so that a GridSearchResult is pickled after a GridSearch phase, which was achieved by adding a new pickle method to the as_grid_search phase function:

```
        # noinspection PyMethodMayBeStatic,PyUnusedLocal
        def make_result(self, result, analysis):

            self.save_grid_search_result(grid_search_result=result)

            return result
```

This pickles an instance of a GridSearchResult. The first problem is that the phase_output.py method:

```
    def __getattr__(self, item):
        """
        Attempt to load a pickle by the same name from the phase output directory.

        dataset.pickle, meta_dataset.pickle etc.
        """

        with open(
                os.path.join(self.pickle_path, f"{item}.pickle"), "rb"
        ) as f:
            return pickle.load(f)
```

This assumes the pickled item is available for all paths the aggregator points to to load a pickle. This means when I try to load a grid_search_result from an aggregator, I get an error as the majority of the paths do not have this pickle file. It works if I filter the aggrregator so the only path is the GridSearchResult, but this isn't ideal.

The next issue is once I have loaded an instance of GridSearchResult, the following meethods causes an exceptioon to be raised:

```
    def __getattr__(self, item: str) -> object:
        """
        We default to getting attributes from the best result. This allows promises to reference best results.
        """
        return getattr(self.best_result, item)
```

If I comment this out, it works. I assume this is used when the pickled instance is loaded, and it is thus causing a clash there given it overrides the default method.

Finally, would it be possible to have a "_lists" variable of the physical parameter centres in the GridSearchResult. The parameter "lists" gives the unit value centres (e.g. (0.5, 0.5), (0.5, 1.0), (1.0, 0.5), (1.0, 1.0)) - but for using the results it'd be easier to have the physical values as well.

**Comment by rhayes777** [comment]
What so you'd rather have None if a grid search result does not exist?

**Comment by rhayes777** [comment]
Pushed to the posteriors feature branch (probably should have been its own branch...)

GridSearchResult now has a physical_lists attribute. Same as lists, just physical.
GridSearchResult pickles should load fine.
If any pickle is not found for a given output during aggregation then None is returned rather than an error being thrown.
