### ISSUE TITLE
Updates to root.log

### ISSUE THREAD

**Issue by Jammy2211** [rhayes777/PyAutoFit#985]
The following config file creates root.log:

https://github.com/rhayes777/PyAutoFit/blob/main/autofit/config/logging.yaml

This contains useful informtion, putting the console output to the file.

However, the file `root.log` is always made in the current working directory of the use, which makes it fairly useless to track.

Could we have it so that `root.log` is always written to the output folder of the search being run?

If a user does not supply a search name (so not hard-disk output) the `root.log` file should not be created.

It should also be customizeable in `output.yaml` if root.log is created.

**Comment by rhayes777** [comment]
In this case we probably want the root filehandler to be off by default (i.e. in the logging.yaml file)
